### ISSUE TITLE
Improve UX on mobile

### ISSUE THREAD

**Issue by charlydelta** [lutris/website#104]
## Updated issue

- Issue: Update the design for mobile to improve UX
- Corresponding MR: #105

## Original RFC for the design study

While surfing on the mobile site of Lutris I noticed several minor issues, for example:

- Lutris brand breaking on small screens
- A lot of wasted space (both horizontal and vertical)
- A lot of clutter (unneeded information, ...)

So I decided to take half an hour and experiment a bit. Below are the results, and I would like to start a discussion on whether I should further pursue development leading to a merge request, with your feedback of course.

Note that the aim for a development in this direction would only be to tweak the mobile version of Lutris.net.

Another minor notes:

- Filter icon instead of a huge list of platforms and genres. The icon should expand a mobile-optimised filter menu.
- I did omit the search function, because there's another open issue discussing about moving the search to a global place.

![design-study](https://user-images.githubusercontent.com/13337480/32148264-81782398-bcf4-11e7-9908-8d6d2526b50e.png)

**Comment by strycore** [comment]
Those changes look great and would be most welcome! :+1:

**Comment by charlydelta** [comment]
Great, I will see if I can already open a WIP MR in the next few hours :)
