### ISSUE TITLE
Several issues with installer revisions

### ISSUE THREAD

**Issue by ghost** [lutris/website#109]
While making a MR for installer revisions, I encountered several issues

- **BUG** If you create an installer, navigate to `/admin/games/installer/` check `published` and save, a new revision will be created with no changes
  - Database bloating
  - Most likely a bug since it doesn't do that if you publish an installer via the installer review pages `/games/installer/review/<game-slug>`
- **BUG/CRITICAL** If you head to `/games/installer/review/<game-slug>`, just select the installer itself on the left (and nothing else) and click delete, it will delete the installer, but all revisions remain in the database
  - Database bloating + **leak!**
  - Even after deleting the installers in the right order, I sometimes have entries left in the table. Didn't try to reproduce yet, though
- **UNCONFIRMED** The table `reversion_revision` seems to be leaking, too. At least there's always data in the table even after I deleted everything. However, this may be by design to log actions
- **UX** Reviewing revisions seems to be highly tedious and uncomfortable. It would be good if we would not allow to select diffs from the same revision to itself, and from one revision to one with a smaller id. You can still select the revisions in whatever order you like, but it should always be displayed in the order `OLD | NEW`

**Comment by soredake** [comment]
@strycore

**Comment by strycore** [comment]
this is resolved in the new dashboard.
