### ISSUE TITLE
Moderation organisation

### ISSUE THREAD

**Issue by ghost** [lutris/website#122]
Several times now I encountered a situation where I didn't want to accept user published games, change suggestions or installers, but I didn't want to reject them either for various reasons.

For example:

- Uncertainty (correctness, etc)
- Accepting something would imply further changes for which we have no time. (For example the Sims 4 change submission which is on hold right now)
- Change suggestions for games which have the (TM) or (R) thing, which got slugifyied - I am not sure if slugs can be changed without breaking something, so all these requests are still pending

I think that it would be great for moderation to have a system where moderators could exchange messages or so, even if it is very primitive. I am thinking of an per-game-basis ticket system, and if there is an issue or something similar a ticket can be created with more information. These messages should be displayed in *every* moderation view.

So we would have a new table called `moderation_ticker` or so, and a N:M relation between a game and a ticket. For the beginning I think it would be enough to just have a text box which is the ticket. Maybe also a title or a dropdown which depicts the scope (for example: `game metadata`, `installer`, ...)

**Comment by strycore** [comment]
Closing this ticket and creating a new one about game issues.
