### ISSUE TITLE
Multiple games publish option in Lutris Administration 

### ISSUE THREAD

**Issue by soredake** [lutris/website#127]

**Comment by soredake** [comment]
https://lutris.net/admin/games/game/?is_public__exact=0

There is only 'Delete selected games' option.

**Comment by charlydelta** [comment]
Just tick the checkboxes and hit "save" - simple as that

**Comment by soredake** [comment]
Save button does nothing, games are not published.

**Comment by charlydelta** [comment]
So it's a Django bug then? I mean, that would be the intended behaviour.

**Comment by strycore** [comment]
Might have been a Django bug. The website is now using Django 2.0, I tested this and it worked as expected.
