### ISSUE TITLE
https://lutris.net/games/installer/submissions filled with entries with non-working 'Delete' button

### ISSUE THREAD

**Issue by soredake** [lutris/website#128]
![24-12-2017_00 35 35](https://user-images.githubusercontent.com/5204968/34323088-a964592c-e831-11e7-9653-839d1545fd7e.png)

**Comment by soredake** [comment]
@strycore can you please fix this? It's very annoying

**Comment by soredake** [comment]
@strycore can you please fix this? It's very annoying

**Comment by strycore** [comment]
Orphan submissions are now automatically deleted before the page loads.
