### ISSUE TITLE
Make draft installers private

### ISSUE THREAD

**Issue by AccountOneOff** [lutris/website#133]
I've had some of my installers broken by other users so having a finished copy on my profile would have been handy. I know downloading it as a json is possible but It'd be better stored on Lutris I think. Just a suggestion.

**Comment by strycore** [comment]
All draft installers are going to be moved from the game page to user profiles

**Comment by strycore** [comment]
Going to consider that fixed now. There are still some quality of life improvement to be made but the basics of private drafts are now deployed.
