### ISSUE TITLE
Installer notes HTML formatting

### ISSUE THREAD

**Issue by AccountOneOff** [lutris/website#135]
Installer notes don't respect HTML formatting.

![screenshot from 2018-02-14 10-43-36](https://user-images.githubusercontent.com/15083452/36221770-ffcf6cc8-1173-11e8-914c-d2dddf047021.png)

**Comment by RobLoach** [comment]
`<strong>` instead of `<b>`?

**Comment by strycore** [comment]
Note that this is not actual HTML but Gtk markup, which is a tiny subset of HTML. It's possible to have a filter in Django that wil only render a list of given tags, this is what we want here.

@RobLoach I think the correct tag in Gtk markup is indeed <b>

**Comment by IngeniousDox** [comment]
Also url links don't seem to be working. Look at: [World of Warcaft](https://lutris.net/games/world-of-warcraft/)

This URL link works fine when you click on install. But you also want it to work on the website.

**Comment by tannisroot** [comment]
It's now fixed.
