### ISSUE TITLE
Change Game Search from thegamesdb.net to mobygames.com

### ISSUE THREAD

**Issue by tobim91** [lutris/website#140]
If I want to submit a Game there is a option to search it on thegamesdb.net but for me there are many games missing I personally had and it is _very very_ slow (sometime it takes **ONE MINUTE** to load the main Page) while mobygames is a little bit quicker and has more or better information about the Game. Also there is an API http://www.mobygames.com/info/api So maybe that could help.

**Comment by strycore** [comment]
Thank you so much for bringing that up, I have waited for the Mobygames API for YEARS.

**Comment by AlexanderRavenheart** [comment]
Has anyone requested the API key yet?

**Comment by AlexanderRavenheart** [comment]
I tested out the MobyGames API in regards to the viability of using it for searching games to be added, and I don't think it it is suitable for that because:
- The search text has to be exact:
    - searching 'night woods' -> no results -> must use 'night in the woods'
    - searching 'red faction guerilla' -> no results -> must use 'red faction: guerilla'
    - searching 'faction red' -> no results -> must use 'red faction'
- There is a low limit to the number of API calls per hour (360, one request every 10 seconds)

**Comment by strycore** [comment]
Still want to have some way to import data from Mobygames. I would like to do a full sync with MobyGames at some point and even with those limitations, it's possible to make more than 250k requests per months.
For real-time search, the limitations might be a problem (but then again, it's not like we're being overwhelmed by people using the game submission form)

**Comment by AlexanderRavenheart** [comment]
For a full sync I suggest we ask for an export of some kind because there is a limit of 100 games per request so it would take forever to run a full sync using the current API. We could optimize it to only request games for platforms we support but that would still be a very long process.

**Comment by strycore** [comment]
it's 2.5 millions of games we can retrieve in a month! I'm not sure they have that much in their databse.

**Comment by strycore** [comment]
We no longer use a search feature reliant on 3rd party services for the game submission and we already did a full import of IGDB. This can be closed.
