### ISSUE TITLE
Add suggestion to screenshot submission page

### ISSUE THREAD

**Issue by AccountOneOff** [lutris/website#145]
It seems more and more users are submitting screenshots for games that don't function properly under Wine creating a sense of false advertisement. Perhaps add a message on the submission page?

Maybe something like: "While uploading non-in-game screenshots isn't prohibited we do strongly encourage you submit your own in-game screenshots."

**Comment by RobLoach** [comment]
> submitting screenshots for games that don't function properly under Wine creating a sense of false advertisement

Which ones?

**Comment by AccountOneOff** [comment]
Game released just last month and has no AppDB entry. https://lutris.net/games/pc-building-simulator/

**Comment by strycore** [comment]
Not sure there's a "best place" to check Wine compatibility. A lot of WineHQ's entries are too old to be relevant with the current version.

I agree with the premise of this ticket, we should encourage screenshots from the game running on Linux only.
