### ISSUE TITLE
Issues with banner upload

### ISSUE THREAD

**Issue by founderio** [lutris/website#147]
After submitting a few game entries I have found these issues:
* Upload without an image does not work. (Error message that the file is empty) You have to select an image file, but even when selecting "Delete image", it is not removed, leading to situations like this:
![image](https://user-images.githubusercontent.com/6136865/38205489-19441eda-36a7-11e8-8432-452fd0a6324d.png)
* This leads to the next issue: Once submitted, removing or changing the image is not possible.
* Another issue: Sometimes the upload just produces black banners:
![image](https://user-images.githubusercontent.com/6136865/38205529-45a9d42e-36a7-11e8-9e28-743837baa175.png)

**Comment by strycore** [comment]
As a user who is submitting a game, I should
- [ ] See an error when trying to submit a game without uploading a banner
- [ ] See an error message if the image I tried to upload is invalid.

As a user who is editing an existing game, I want to:
- [ ] Change the existing banner
