### ISSUE TITLE
Add GogDB to the "See also:" section on game pages

### ISSUE THREAD

**Issue by AccountOneOff** [lutris/website#151]
Found this handy site a while ago. Could it also be used to pull icons and banners? 

https://www.gogdb.org

**Comment by RobLoach** [comment]
Very cool. I could see us using this for the Installers too.

**Comment by strycore** [comment]
It's a website that shows the GOG API on a website. There's nothing we don't already have already

**Comment by AccountOneOff** [comment]
@strycore it's still a good resource for exe paths and dependencies. E.g. https://www.gogdb.org/product/1435068351/build/51118887472183245
