### ISSUE TITLE
Lutris Forums keeps sending "summary" emails even after unsubscribing

### ISSUE THREAD

**Issue by talklittle** [lutris/website#156]
Since yesterday, I've gotten 5 Lutris Forums summary emails. I have clicked every link I can find to unsubscribe, and also updated my preferences at https://forums.lutris.net/my/preferences/emails to no avail.

Edit for more info:

I visit the unsubscribe link in the email which brings me to `https://forums.lutris.net/email/unsubscribe/<random id>` and then hitting the unsubscribe button on that page, I get redirected to `https://forums.lutris.net/email/unsubscribed?email=my+email@example.com` but the page says "Oops! That page doesn’t exist or is private."

**Comment by strycore** [comment]
This was likely due to the forums not being able to send emails for a few days and a queue of emails got sent when I fixed the issue on the server.

Please re-open if this continues to be an issue.

**Comment by talklittle** [comment]
@strycore I just received a new "summary" email linking to https://forums.lutris.net/t/how-frequent-is-dxvk-getting-updated/2011 which was created 6 hours ago. Can you please reopen this issue? (I cannot reopen since it was closed by a repository owner.)

**Comment by talklittle** [comment]
The first link `https://forums.lutris.net/email/unsubscribe/<random id>` renders properly

![lutris-forums-unsub-1](https://user-images.githubusercontent.com/87961/40146112-3a12ed32-5919-11e8-89b4-9a0e0e5e3ed0.png)

But then after I click unsubscribe, having either one or both checkboxes checked, I get redirected to the 2nd URL `https://forums.lutris.net/email/unsubscribed?email=my+email@example.com` which gives a 404. I made sure my Lutris Forums account is logged in on this browser session.

![lutris-forums-unsub-2](https://user-images.githubusercontent.com/87961/40146171-5f56a098-5919-11e8-9227-0c682d207a2a.png)

**Comment by strycore** [comment]
Tried those links and didn't have any issue but then, I'm an admin on the forums so I might be able to have access to different things.

Make sure you are logged in on both the website *and* the forums before unsubscribing as Discourse doesn't support unsubscribing i you're not logged in: https://meta.discourse.org/t/unsubscribing-from-email-notifications-without-login/28581

**Comment by talklittle** [comment]
I'm logged in on both and same error message. :/

The summary emails seem to have stopped though. I had been getting one immediately after each new post. Now I see there are 1 or 2 new forums posts since my last summary email, and I haven't gotten an email for them, so that's good. Thanks for looking into it, I'll close the issue and assume it was a temporary glitch.

**Comment by talklittle** [comment]
One week, no emails. Phew.
