### ISSUE TITLE
LutrisWiki - We need a wiki with links from each game.

### ISSUE THREAD

**Issue by IngeniousDox** [lutris/website#160]
I replied to someone in [forum](https://forums.lutris.net/t/create-something-like-faq-section-on-the-site-covering-basic-lutris-questions/2036/2). So shamelessly copying this here. Since you always say Strider: If it isn't on Github, I won't see it.

I fully agree. I have been asking for this to Strider for a year now. But he has been busy the past year. He seems to have some time now to do stuff.

In the mean time I started using the Github Wiki to put in my “answers” to Blizzard games I make installers for. Seems to have seriously reduced the number of questions I get on Discord.

My suggestion would be this: LutrisWiki

And then the option of adding links to the Wiki on each gamepage. With an “autolink” to a predefined name based on the game name. I think a wiki is better then a section on each game page. This will make the game pages “cleaner” since we are now adding a lot of extra stuff to each installer, which would end up on the wiki. And we then just have to add notes for specific stuff for that installer.

The ultimate goal would be make this LutrisWiki the go to place for Linux Gaming. (Just like ArchWiki is the go to place for Linux question in general).

**Comment by RobLoach** [comment]
There are two places that we can use...

1. There's the GitHub wiki, already used for a few installers.
2. The Notes section of installers can have some useful stuff in there.

**Comment by IngeniousDox** [comment]
Yes, both are completely inadequate. I made most of those github pages...however Github pages shouldn't be for the games. It should max be for Lutris itself. How to set up Lutris. Debugging. Options etc.

And installers should remain small. And not force people to replicate instructions constantly. Especially when instructions apply to multiple games you get data replication.

For Lutris platform in general, a LutrisWiki where we can put that information without data duplication seems much better.

**Comment by RobLoach** [comment]
We could start a subsection in GitHub pages for them. I just know wikis can grow to a unmaintained state pretty quickly.

**Comment by IngeniousDox** [comment]
WineHQ truly sucks for information. It removes anything Lutris related anyways.

Had a talk on Discord with Strider about it already. He agrees that github wiki is not good enough. He wants to make his own wiki. I came up with this, and he is interested in it:

- Own wiki, with own SSO, so you can use your Lutris username for the wiki.
- Make pages on the wiki.
- Tag the pages with game names
- Then you can automatically generate a "mini-wiki" on each game page with pages that are tagged for that game.
- Other tag types are possible: Publisher tags, Tweaks tag, FPS tag, NVidia tag etc.
- You can show clearly how old information is, perhaps with a stopsign color based on how old information is. Green for under 3 months, orange for 3 to 6, red for over 6 months since last edit for example.

Rest will need to be worked out. But the big plus with this is:

1. No data replication, you put info in 1 place, and it gets linked to the game pages.
2. Installers can get smaller since issues can be put in Wiki.
3. Updating info can be done in 1 spot (side effect of no data replication, but a very important side effect).
4. Its easy to add see how old information is.

**Comment by strycore** [comment]
Here: https://www.pcgamingwiki.com/wiki/Home

**Comment by strycore** [comment]
The wiki pages that we already have are really confusing rather than helpful and the goal of Lutris is to simplify and automate the installation of games, not make it more complex.

Any info that is actually useful should go on PCGamingWiki, this is where I go look for information when I need it. PCGamingWiki already has a lot of resources on Linux.
