### ISSUE TITLE
Debian-based install instructions: apt instead of apt-get

### ISSUE THREAD

**Issue by xalmat** [lutris/website#161]
The "apt-get" command in Debian-based distributions has been deprecated in favor of the "apt" command. Although "apt-get" still works, "apt" should be the preferred command.

For the install instructions for Debian, Ubuntu, and Mint, simply change anywhere that says "apt-get" to "apt'

**Comment by strycore** [comment]
There are no plans to deprecate apt-get and other apt-* commands, the apt command provides higher level access to package management and is friendlier to use when typing in a terminal but the apt-* commands are still valid and needed for more advanced commands. (See: https://manpages.debian.org/jessie/apt/apt.8.en.html )

We might replace the apt-get command with apt at some point but we'll first want to make sure that every supported distribution has migrated.
