### ISSUE TITLE
Keep revisions of previously published installers

### ISSUE THREAD

**Issue by DrDoctor13** [lutris/website#163]
When testing games that may have worked at a point or may not work anymore, looking at past revisions of scripts can be very beneficial for tracking changes and possibly adding them to existing installations to improve stability. Showing authors of each revision and change also disincentivizes bad edits due to each user being publicly viewable, meaning that if a bad edit gets published, it can be properly reported instead of starting an editing war.

**Comment by strycore** [comment]
We can put that in place with what we already have with installer submissions.

**Comment by strycore** [comment]
A snapshot of installers is now kept every time a moderator accepts a submission.
