### ISSUE TITLE
Improve UX for installer submission

### ISSUE THREAD

**Issue by sigmaSd** [lutris/website#166]
Hi, I did an install script for a bunch of games yesterday, I just loved how powerful the tools are. I just found a couple of issues, so I'm pointing them out. 
When writing a draft and saving it without sending it to moderation, when I edit the draft again I don't see my changes immediately but I have to wait for moderation, so I workaround it by deleting the draft and making a new one. 
Draft experimentation shouldn't need moderation till I hit the submit for moderation button. 
Second problem when I fork an existing script, the draft dosen't show the changes but just mirror the original till it gets approved, so I have to workaround it by forking manually aka making a new script and copy pasting.

**Comment by sigmaSd** [comment]
One more issue, when writing a draft "Test this installer " button dosen't appear after I save it and open it again with edit.
I have to make any edit and save it again so this button appears.

**Comment by strycore** [comment]
I've made some change to the Save draft and Test this installer button, this should fix the issue.
