### ISSUE TITLE
[Suggestion] A DXVK compatibility list page

### ISSUE THREAD

**Issue by AccountOneOff** [lutris/website#168]
Thoughts on making an RPCS3-esque compatibility list for DXVK on the website? Markdown has it's limitations and the DXVK dev has expressed interest in a compat list similar to RPCS3.

**Comment by RobLoach** [comment]
My google-ing I found...

- https://www.gamingonlinux.com/wiki/DXVK_Compatibility_List
- https://ethercalc.org/1d9vtis8r2eb

Might live well in https://github.com/lutris/lutris/wiki/How-to:-DXVK https://github.com/doitsujin/dxvk/wiki .
