### ISSUE TITLE
Steam library web sync does not work

### ISSUE THREAD

**Issue by breversa** [lutris/website#173]
Hi,
When trying to link my Steam library from the Steam widget on https://lutris.net/user/, after logging in on Steam, I get a perpetual "Your Steam library is being synced with your Lutris account" message, and no game is ever imported.

My Steam profile is public.

**Comment by nvma** [comment]
Hey guys, any info on this? Thanks for your work!

**Comment by strycore** [comment]
please reopen if you still experience issues. This should be solved

**Comment by Iiridayn** [comment]
https://lutris.net/user/Ged_Crimsonclaw/library/ - still not working, tried the sync twice last night, still nothing there. Don't see any GitHub UI for re-opening this.
