### ISSUE TITLE
Let users submit Steam games

### ISSUE THREAD

**Issue by strycore** [lutris/website#175]
We currently advise that user submit their Steam games from the Steam sync feature. That can be a problem if the user doesn't have the game on Steam but on another platform such as GOG.

1. Remove "Don't publish Steam links warning"
2. Add a "This game is not on Steam" checkbox, that is checked by default
3. When this checkbox is unchecked, a text input appears, letting users paste the Steam URL
4. When the form is submitted, the SteamID is extracted from the Steam URL

**Comment by testman42** [comment]
Wait, doesn't Lutris database sync with [SteamDB](https://steamdb.info/) which already has everything that is on Steam, effectively removing the need for people to manually add new Steam games into Lutris database?

**Comment by strycore** [comment]
No, we sync with the Steam API itself. New games are added by syncing the user libraries which means that we have the game if at least one person has the game in their Steam library.

I'll probably add a script that isn't dependent on the user libraries, SteamDB is an ideal candidate for grabbing Steam games.

**Comment by djibux** [comment]
#375 shows that some games won't sync even if they are in one person's library.

**Comment by strycore** [comment]
We now have code that syncs the whole content of the Steam store so this feature is no longer needed.
