### ISSUE TITLE
Update validator for missing "prefix: $GAMEDIR" in wine/steam installers

### ISSUE THREAD

**Issue by AccountOneOff** [lutris/website#176]
Add validation check for `prefix:` when creating a prefix and when using winetricks

This passed the validator:

![screenshot from 2018-06-30 18-07-25](https://user-images.githubusercontent.com/15083452/42130150-7edcfb16-7c90-11e8-9e7d-10675d3121cd.png)

**Comment by sigmaSd** [comment]
And the path to prefix should be validated to be relative to $GAMEDIR, someone got his partition deleted cause of the installer [https://forums.lutris.net/t/lutris-deleted-my-whole-partition-data/3853/9](https://forums.lutris.net/t/lutris-deleted-my-whole-partition-data/3853/9)

**Comment by strycore** [comment]
Specifying the prefix is no longer needed as Lutris will automatically default to $GAMEDIR if no value is given:

```
            data["prefix"] = data.get("prefix") \
                or self.installer.script.get("game", {}).get("prefix") \
                or "$GAMEDIR"
            data["arch"] = data.get("arch") \
                or self.installer.script.get("game", {}).get("arch") \
                or WINE_DEFAULT_ARCH
```
