### ISSUE TITLE
Update Discord link

### ISSUE THREAD

**Issue by strycore** [lutris/website#182]
This link doesn't point to the rules channel but to the Lutris channel instead

https://discord.gg/C3uJjRD

**Comment by duhow** [comment]
* accounts/views.py
* templates/base.html
* templates/common/about.html
* templates/common/faq.html
* templates/emails/game_accepted.html
* templates/emails/game_accepted.txt

**Comment by strycore** [comment]
Thanks for the recap, that helped catch a typo in the Discourse code :D 
Now the implementation is cleaner, the Discord URL is in the Django settings in a single location.
