### ISSUE TITLE
Weird pointer behavior when creating installers

### ISSUE THREAD

**Issue by tannisroot** [lutris/website#184]
For some reason, the pointer in installer content field started behaving a bit strange.
If I place the pointer at the end of the line, which will have a space at the end, it will get misplaced.
![Gfycat](https://thumbs.gfycat.com/CraftyEnchantedAmericanmarten-size_restricted.gif)
This is very annoying and creates multiple issues when creating or editing installers (like lines not copy-pasting correctly), and I don't remember this happening before.

**Comment by tannisroot** [comment]
The issue was caused by lacking certain fonts. Installing ubuntu-font-family solved it.

**Comment by tannisroot** [comment]
While it was visually fixed, it's still an issue when copying lines.

**Comment by tannisroot** [comment]
It seems that I can only reproduce this with Gnome's default monotype font, `Monospace`.
If I set default monotype font in Chromium to `Ubuntu Mono`, the issue is not reproducible.

**Comment by strycore** [comment]
Don't know if this is still an issue but I haven't experienced it in a very long time.
We plan to migrate to diff2html at some point in the future so this can be closed.
