### ISSUE TITLE
Can't run the website with Docker

### ISSUE THREAD

**Issue by Medath** [lutris/website#191]
I wanted to play around with the website for a bit so I tried to set it up with docker.

However, during the build of the image there appear a few error messages stating that python3 is not available (and a few other error messages as well). When trying to start a new container despite these errors, it just exits immediately also stating that python3 can't be found

I tried adding python3 and python3-pip to the apt line in the Dockerfile, and while that prevented the above error, it led to a whole bunch of other issues like certain modules not being found or python scripts being run with the wrong python version during the image build.

[Here's a log of a session, recorded on a fresh Ubuntu 16.04 LTS Desktop VM (and Docker CE installed via the docker repositories). It becomes interesting at roughly line 2200](https://gist.github.com/Medath/fa7c5858129dfe85b3bd60fbddac7ed0)

It should also be noted that I'm not very experienced in working with Docker or setting up webservers in general, so there's a good chance I'm doing something wrong here.

**Comment by Holzhaus** [comment]
I can reproduce this problem.

**Comment by Zeioth** [comment]
I can reproduce this problem. This is the output of the command 

    sudo docker run --name lutrisweb -it -p 8000:8000 lutris/website

[zeioth@zeioth-pc website-master]$ sudo docker run -p 8000:8000 --name lutrisweb -it lutris/website
./manage.py runserver 0.0.0.0:8000
/usr/bin/env: 'python3': No such file or directory
Makefile:10: recipe for target 'run' failed
make: *** [run] Error 127

**Comment by BurningFool** [comment]
The dockerfile isn't installing python3, which is at least what's causing the issue for manage.py

**Comment by strycore** [comment]
diff --git a/Docker/install.sh b/Docker/install.sh
index d82ebde..db963e6 100644
--- a/Docker/install.sh
+++ b/Docker/install.sh
@@ -11,4 +11,4 @@ make sysdeps
 make db
 make client
 make docs
-pip install Faker
+pip3 install Faker
diff --git a/Dockerfile b/Dockerfile
index 17c4237..c863656 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -1,7 +1,9 @@
 FROM ubuntu:16.04
 MAINTAINER Joonatoona
 
-RUN DEBIAN_FRONTEND=noninteractive apt-get update && apt-get install -y git curl python python-pip imagemagick memcached libmemcached-dev mercurial bzr
+ENV LC_ALL=C.UTF-8
+
+RUN DEBIAN_FRONTEND=noninteractive apt-get update && apt-get install -y git curl python3 python3-pip imagemagick memcached libmemcached-dev mercurial bzr
 
 WORKDIR /app
 ADD . /app
diff --git a/Makefile b/Makefile
index 6f71f96..11de2b7 100644
--- a/Makefile
```
+++ b/Makefile
@@ -28,7 +28,7 @@ jenkins:
        ./manage.py jenkins $(test)
 
 sysdeps:
-       sudo apt-get -y install libpq-dev python-dev nginx supervisor rabbitmq-server libjpeg-dev libxml2-dev libxslt1-dev
+       sudo apt-get -y --allow-unauthenticated install libpq-dev python-dev nginx supervisor rabbitmq-server libjpeg-dev libxml2-dev libxslt1-dev locales libffi-dev
        pip3 install -r config/requirements/production.pip --exists-action=s
```

**Comment by strycore** [comment]
The updated Dockerfile should now be able to launch the website
