### ISSUE TITLE
Allow genre and platform conditions to be applied together in search

### ISSUE THREAD

**Issue by fusion809** [lutris/website#198]
Hi,

The concept of Lutris is great, but there is something I'd like to request. Could you's please allow us to apply platform and genre conditions together? Like presently I'd like to search for Linux-compatible RTS games only, but I can only search for [RTS games](https://lutris.net/games/genre/rts/) (in which RTS games compatible with any platform will appear) OR [Linux-compatible games](https://lutris.net/games/platform/linux/) (in which Linux-compatible games of all genres will appear). 

Thanks for your time,
Brenton

**Comment by AlexanderRavenheart** [comment]
Hello, yes this is planned.
I already made a PR for revamping the My Library page that includes improved ordering, filtering and pagination of content.
Once that is merged I will also make same changes to main Games page.
