### ISSUE TITLE
Let mods sent installers back to draft

### ISSUE THREAD

**Issue by telanus** [lutris/website#206]
Give us mods a box we can fill in when one reject a "Change submission" that gets sent to the submitter, if one need to redirect the submitter. Have seen a few where the description get's rewritten into a bug report/help request. Would be better if one can tell them to go to the forum or github to submit a issue there.

**Comment by strycore** [comment]
That would have to be implemented after we have added the notification system.

**Comment by strycore** [comment]
The dashboard now has a field that can be used to leave a review on an installer. If it's filled, an email will be sent to the script author, otherwise the installer will be reverted back to draft.
