### ISSUE TITLE
URL encoding bug

### ISSUE THREAD

**Issue by basxto** [lutris/website#210]
I entered `black &  white` into the search field and went to https://lutris.net/games/?q=black+%26+white.
`black+%26+white` is correct and the expected behavior.
But when I click on `However, 1 unpublished game does. `, I end up on https://lutris.net/games/?q=black%20&%20white&unpublished-filter=on.
Effectively the search query got changed to just `black`

**Comment by strycore** [comment]
with the current search system, this no longer happens
