### ISSUE TITLE
[Suggestion] Import games from MobyGames, drop the Submit new game feature

### ISSUE THREAD

**Issue by AlexanderRavenheart** [lutris/website#212]
I believe a full partnership with MobyGames could prove to be a big boon for both projects.

Here is my suggestion for the MobyGames integration:
- Use MobyGames API to get full list of games and their full info (title, description, platforms, etc.) and fill the Lutris DB - done only once
- Schedule a daily or weekly task on server to import new or changed games from MobyGames
- Redirect users to MobyGames for adding new games or filling out more information (description, platforms, etc.)

**Comment by PopeRigby** [comment]
I don't think this is a good idea, because of the fact that MobyGames' database is proprietary. Having an open database of games on lutris.net is useful.

**Comment by AlexanderRavenheart** [comment]
> I don't think this is a good idea, because of the fact that MobyGames' database is proprietary. Having an open database of games on lutris.net is useful.

There was never any mention of dropping the lutris database. This is a proposal for an automatic way to add games to the Lutris DB with information retrieved from MobyGames.
In return we provide a link to MobyGames where users who are interested can go and add new games/information/screenshots/etc.

This way, regardless if a game is added directly on the Lutris site or indirectly through MobyGames we will have a much more complete collection of games available.

**Comment by strycore** [comment]
Exactly, I would like to have MobyGames as a source of data for game imports.
Currently, we can automatically create games from Steam (with minimal info), MobyGames would help so much more!

I don't know if there will be a time where we can totally drop the submit game form (especially not if we're looking into features designed for game developers or publishers) but we can at least strongly minimize its usage.

**Comment by PopeRigby** [comment]
I understand. Is closed data like that able to be imported to the open database on lutris.net without compromising the license?

**Comment by strycore** [comment]
Right now, I'm building models to store games returned by MobyGames or other services, this data would only be used internally and wouldn't be open like our API is.

**Comment by strycore** [comment]
I don't know if integrating with MobyGames will be useful now that we have sync with IGDB. Maintaining both sound more like an hassle than anything else.
Also, we shouldn't remove the ability to submit new games.
