### ISSUE TITLE
Main Page

### ISSUE THREAD

**Issue by AlexanderRavenheart** [lutris/website#214]
Here is a suggestion for a redesigned main page.

- A gallery with lightbox support showing the different interface elements/features of Lutris.
- A 3 columns section for displaying various social feeds (blog, twitter, facebook?) with fixed size and nice modal for display more (to show full content of post) so that long posts (like the ones on the blog) don't make this section too long.
- A gallery/list with following sections:
  - recently submitted/updated games
  - new/updated installers

**Comment by strycore** [comment]
pretty close to what I had in mind:
Here is a suggestion for a redesigned main page.

* A gallery with lightbox support showing the most popular / games we support (LoL, WoW, Minecraft, Warframe, Witcher 3...)
* A 3 columns section showing the features of lutris + link to Patreon
* A gallery/list with following sections:
    More manually curated games
    Recently submitted/updated games and / or installers
* Excerpts of posts on the Patreon website (replacing the news articles), Twitter feed.

**Comment by AlexanderRavenheart** [comment]
>     * A gallery with lightbox support showing the most popular / games we support (LoL, WoW, Minecraft, Warframe, Witcher 3...)

I think this would be better suited on the top part of the Games page.

**Comment by strycore** [comment]
This is the only part I'm 100% sure about. The games that people care about are being shown as the first thing people see on the website.

**Comment by strycore** [comment]
The rationale behind that is that I want to show immediately what Lutris is capable to do, before showing how we do that. Otherwise, users might ask why is this even a thing. Showing right upfront that Lutris is capable of running LoL, Warframe or Witcher 3, everyone knows what we're up to. Some screenshots of a Gtk3 GUI are a lot less impressive and don't relay the information we'd like to convey. Having features explained below in would let us go more in depth, after grabbing the attention of the user.

**Comment by AlexanderRavenheart** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;}  Well, Lutris is more of an aggregator and manager of games, as the actual running of said games is up to the runners which are integrated with Lutris.It would be a misconception to make users believe Lutris is running the games instead of the actual runners, and that would lead to bugs being reported to Lutris instead of the corresponding runners whenever some issue is outside of Lutris' responsibilities.                                                                                                                                                                                                                                                                                                                From: notifications@github.comSent: 18 September 2018 10:29 amTo: website@noreply.github.comReply to: reply@reply.github.comCc: michiduta07@gmail.com; author@noreply.github.comSubject: Re: [lutris/website] Main Page (#214)  The rationale behind that is that I want to show immediately what Lutris is capable to do, before showing how we do that. Otherwise, users might ask why is this even a thing. Showing right upfront that Lutris is capable of running LoL, Warframe or Witcher 3, everyone knows what we're up to. Some screenshots of a Gtk3 GUI are a lot less impressive and don't relay the information we'd like to convey. Having features explained below in would let us go more in depth, after grabbing the attention of the user.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by strycore** [comment]
I've been fighting the idea that Lutris is "only" a game manager/launcher for 9 years now. The project was meant to be a gaming platform from day 1, I wouldn't have started a game launcher project. 
In that respect, we do have a responsibility to make games run on Linux, as it is the sole purpose of the project.  

We are not misleading anyone when we say that the project's purpose is to run the games shown on the home page, among other ones. Lutris' runners are just as part of the project as the Gtk client, the runtime, the REST API, install scripts and other goodies such as DXVK. It's all part of a same project, it's just one inseparable bundle.

**Comment by strycore** [comment]
this is done
