### ISSUE TITLE
Tags break if they're at the beginning of a description 

### ISSUE THREAD

**Issue by AccountOneOff** [lutris/website#223]
See Sniper Elite 4: https://lutris.net/games/sniper-elite-4/

Shows up fine in the client and works if I put `-` in front of it.

**Comment by AccountOneOff** [comment]
This isn't exclusive to links but all tags.

<b>Virtual desktop</b>

![screenshot_2019-02-12 sleeping dogs definitive edition](https://user-images.githubusercontent.com/15083452/52675721-904a9300-2edc-11e9-81b6-c9ccd26a476a.png)

**Comment by strycore** [comment]
Tags are no longer accepted in the description or notes field. Hyperlinks are automatically added in the lutris client
