### ISSUE TITLE
Add check to validator if downloaded files are used

### ISSUE THREAD

**Issue by tannisroot** [lutris/website#228]
I've seen some installers that download an installer for the game, for example:
files:
```
files:
- installer: https://foo.bar/game_install.exe
```

and then call for the installer by not using the `installer` alias, but by calling its filename:

```
- task:
    executable: installer
    name: game_install.exe
    prefix: $GAMEDIR
```
(**game_install.exe** here is wrong, should be **installer**)

Another a common issue is installers using an alias from the documentation (like `file1`) instead of what what specified in `files` section, or not using some of the entries from there at all.

It would be nice if validator checked if the files that installer downloads are even used (and also if requested files get downloaded at all) in any of the tasks to avoid stuff like this.

**Comment by strycore** [comment]
Added a validator to make sure every file is used
