### ISSUE TITLE
Don't show drafts to the moderators

### ISSUE THREAD

**Issue by tannisroot** [lutris/website#232]
I don't quite understand why drafts are treated just like installers that were submitted for moderation. As a moderator, it's very frustrating when I get a bunch of unfinished or broken drafts in my email. It wastes my time that I could spend on reviewing installers that are finished.
Instead, I think it would be better to only show them to the actual creator of the installer.

**Comment by strycore** [comment]
The new dashboard now shows a page with only the submissions

**Comment by strycore** [comment]
still have to update the email though

**Comment by strycore** [comment]
eh, forget about the email, the whole daily digest is too slow anyway.
I'll add Discord notifications, it will be better for everyone.
