### ISSUE TITLE
Add issue template for installer issues

### ISSUE THREAD

**Issue by AccountOneOff** [lutris/website#239]
Similar to this but on the website: https://github.com/doitsujin/dxvk/blob/master/issue_template.md

- Distro version
- GPU/GPU drivers
- `lutris -d` log and, if Wine/Winesteam game, Wine log
- Lutris game settings (Game, Runner, System options)

**Comment by strycore** [comment]
No. this is not going on the installer issue tracker. it would produce horrible results visually. 
I plan having a bug reporting tool *inside the client* that will collect that info and submit it to the website.
