### ISSUE TITLE
Make "Reason" field mandatory

### ISSUE THREAD

**Issue by tannisroot** [lutris/website#242]
It would greatly improve the lives of moderators if explaining the reason of the edit in the "Reason" field was mandatory (meaning it wouldn't let you submit it with a blank field), as figuring out on your own what the submission improves/fixes is time consuming and sometimes even frustrating.

**Comment by strycore** [comment]
if it isn't clear what the change is doing, just reject it. We'll have better workflow to handle discussions between mods and contributors. Experienced users or mods submitting their own installers would only be more annoyed by an extra mandatory field and it doesn't guarantee that the field actually contains useful info.

**Comment by tannisroot** [comment]
That's a fair point.
