### ISSUE TITLE
No indicator that an installer is "protected"

### ISSUE THREAD

**Issue by AccountOneOff** [lutris/website#244]
With https://github.com/lutris/website/commit/dba5b2c37abeb8e12d64480b9604c71dcd0b8a89 "Installer modification is restricted" is broken. New installers can still be written. Also I see there's no indication that an installer is "protected". Here the [DXVK installer for Fallout 4](https://lutris.net/games/fallout-4) is protected but no visual indicator is given.

https://lutris.net/admin/games/installer/7504/change/

**Comment by strycore** [comment]
With private installers, we should be able to phase out the installer restricted flag. I'm closing this now since we're currently at a state where this is no longer an issue.
