### ISSUE TITLE
Games page taking a day and a half to load

### ISSUE THREAD

**Issue by AccountOneOff** [lutris/website#246]
https://lutris.net/games used to be fast to open but now it takes 10+ seconds to open.

**Comment by tannisroot** [comment]
Can confirm.

**Comment by strycore** [comment]
I need to get my shit right regarding caching

**Comment by strycore** [comment]
![hopla](https://user-images.githubusercontent.com/280336/49682337-84b79780-fa67-11e8-8bb0-cd5de573e0b3.jpg)
