### ISSUE TITLE
Can't filter search results by platform

### ISSUE THREAD

**Issue by tannisroot** [lutris/website#253]
How to reproduce:
1. Open Games section: https://lutris.net/games/
2. Select a platform (for example, Windows): https://lutris.net/games/platform/windows
3. Type in the name of game into `Search` box
4. Get 404 error: https://lutris.net/games/platform/?q=The+Sims

**Comment by Medath** [comment]
It seems like the chosen platform gets lost in the last link.
If you write https://lutris.net/games/platform/windows/?q=The+Sims instead of https://lutris.net/games/platform/?q=The+Sims the search works correctly

**Comment by filbo** [comment]
Came here to report this...

It 'works' (breaks) both ways, the other way being:

1. Go to https://lutris.net/games
2. Type 'The Sims' into the search box => https://lutris.net/games/?q=the+sims
3. Click on 'Windows' in the palette of Platforms => https://lutris.net/games/platform/windows
-- expected to reach https://lutris.net/games/platform/windows?q=the+sims

Other combinations also break; e.g. choose Windows, then '[x] Show unpublished games' => broken URL; start with '[x] Show unpublished games', choose Windows => https://lutris.net/games/platform/windows (without unpublished games).
