### ISSUE TITLE
[possible bug] greating a game entry not uploading image

### ISSUE THREAD

**Issue by telanus** [lutris/website#256]
When you create a new game entry and submit, it happens every now and then that it fails to upload the banner image, it's unfortunately not consistent in being triggered.once you finish filing in all the entries, chose the banner and press submit, it normally go thru, but once in a while it'll come back and claim that there is no banner, after choosing the same banner, and after resubmitting it might came back that it again failed to "notice" the banner. The most I had to resubmit an entry is twice (thus submitting the same entry three times)

**Comment by tannisroot** [comment]
Can you attach the banner you used to reproduce it?

**Comment by telanus** [comment]
Seems After doing a few additions where everything is working, I closed this as it seemed that the bug wasn't biting anymore, then the next one get the bug to happen.

uploaded the banner here: https://imgur.com/1lUoZNc

it's one I created, the others I made tonight all worked, this one was rejected at the first go, but second go it was accepted

**Comment by telanus** [comment]
OK found out something, that it might be due to GIMP. If these options are checked, when saving as PNG, 

![2019-09-17 0245](https://user-images.githubusercontent.com/19357986/65045534-44266c00-d95f-11e9-9095-f7fa593353e1.png)

it will cause the bug a lot more than when these options aren't checked. With it checked it can take three or four tries to upload the image, with these option unchecked it uploads almost on the first try. 

The options being ticked seems to be the default

**Comment by strycore** [comment]
With our updated code, the image conversion looks like it's much more reliable.
If this ever happen again, don't forget to attach the incriminated file to the ticket, otherwise there's not much that can be done.
