### ISSUE TITLE
Add a check to validator if the arch for a wine version was specified.

### ISSUE THREAD

**Issue by tannisroot** [lutris/website#260]
I've seen quite a few installer that don't specify the architecture of the wine version.
For example
```
wine:
  version: tkg-3.21
```
Which is wrong, because it should be `tkg-3.21-x86_64`, otherwise the installer will fail as it will look for a non-existing version.
As a solution, a check should be added to the validator to ensure the specified wine version has a valid architecture (`x86_64` or `i386`).

**Comment by strycore** [comment]
The installer should guess the architecture, but yeah, I still have to do that.

**Comment by strycore** [comment]
Only valid wine versions (which we reference in the API) can be referenced in scripts
