### ISSUE TITLE
[Feature] Accept Donations via LibrePay

### ISSUE THREAD

**Issue by gjhklfdsa** [lutris/website#263]
**Description**: Accept donations via [LibrePay](https://liberapay.com/).

![Alt Text](https://media.giphy.com/media/hUVybAnJlnp7O/giphy.gif)

**Comment by tannisroot** [comment]
Didn't the project have serious issues with payments not too long ago?

**Comment by gjhklfdsa** [comment]
> Didn't the project have serious issues with payments not too long ago?

Not that I'm aware of. Payments have always gone through when I used it. :)

**Comment by strycore** [comment]
It's now available! https://liberapay.com/Lutris/
