### ISSUE TITLE
Indicate that you have to be logged-in to reply to issues

### ISSUE THREAD

**Issue by tannisroot** [lutris/website#264]
Currently, you can press reply, type it in and press "Submit", but it won't do anything.
This is bad behavior and there should be some kind of error that pops up if you try to reply without being logged in.
![peek 2019-01-03 01-36](https://user-images.githubusercontent.com/10602045/50616158-54450b00-0ef8-11e9-86f6-5d5f4873076d.gif)

**Comment by sparr** [comment]
Console output:

Failed to load resource: the server responded with a status of 401 ()
createError.js:16 Uncaught (in promise) Error: Request failed with status code 401
    at e.exports (createError.js:16)
    at e.exports (settle.js:18)
    at XMLHttpRequest.p.(/games/epic-games-launcher/anonymous function) (https://lutris.net/static/installer-issues.umd.min.544c3495a645.js:46:3891)

**Comment by strycore** [comment]
The issue system has been removed
