### ISSUE TITLE
Make text in descriptions visually stand out.

### ISSUE THREAD

**Issue by tannisroot** [lutris/website#265]
As an installer creator, I use descriptions to deliver important information to the user to ensure the game works well. Unfortunately, descriptions do not do that job very well right now.
I think the reason for that is that the text is just too dark compared to the background. Personally, I think it should be just a bit lighter to stand out more. Examples:
How it looks right now:
![image](https://user-images.githubusercontent.com/10602045/50616402-607d9800-0ef9-11e9-9ba7-321db690dba8.png)
How it can look:
![image](https://user-images.githubusercontent.com/10602045/50616641-60ca6300-0efa-11e9-9cda-681eb8834f28.png)
Even though the difference is not that big, for me it feels much more visually appealing and grabs more attention.
Since colors may look different in various browser, I should note that I use Chromium.

**Comment by strycore** [comment]
fixed
