### ISSUE TITLE
Banners with alpha channel become broken

### ISSUE THREAD

**Issue by tannisroot** [lutris/website#269]
Whatever currently processes banners from Lutris clearly doesn't like transparent images (with alpha channel):
![screenshot from 2019-01-13 15-30-20](https://user-images.githubusercontent.com/10602045/51085319-4721ea80-1748-11e9-8da0-6abe9f3e8138.png)
This is just one example, each time it breaks in very different ways.
Also, black background looks rather ugly. It should probably be changed to white.

**Comment by testman42** [comment]
Can confirm.
![](https://renegade-x.com/uploads/monthly_2016_08/logo_min.png.e69579e01e3ca5f6be40a08bb42b3543.png)
became
![](https://lutris.net//games/banner/renegade-x.jpg)
(file URL is `https://lutris.net//games/banner/renegade-x.jpg`)

I made an edit that looks a bit better and uploaded it.
![](https://lutris.net/media/cache/de/e0/dee0e5e18424d901fb7a20761c04b66c.jpg)
(file URL is `https://lutris.net/media/cache/de/e0/dee0e5e18424d901fb7a20761c04b66c.jpg`)
and the game [site itself](https://lutris.net/games/renegade-x/) uses it fine, but [search results](https://lutris.net/games?q=renegade+x), either on website or in Lutris, use the old messed up image.

**Comment by strycore** [comment]
There is now an explicit conversion to RGB (from RGBA or whatever else). The Pillow library will default to a black background. If that's not what is desired, the image should be converted before being uploaded to lutris.
