### ISSUE TITLE
convert tosec entries to lutris game

### ISSUE THREAD

**Issue by strycore** [lutris/website#27]

**Comment by AlexanderRavenheart** [comment]
@strycore What is this issue about? What are tosec entries?

**Comment by RobLoach** [comment]
TOSEC is a database of hashes of binary files. There are many databases like this out there... TOSEC, Advancescene, GoodTools, No-Intro, etc. [libretro-database](https://github.com/libretro/libretro-database) indexes a few of them for RetroArch.

**Comment by AlexanderRavenheart** [comment]
So how is this relevant to the website? What is that used for?

**Comment by RobLoach** [comment]
I believe to automatically index all the TOSEC entries on the site. I think Strider wants to make Lutris scan your filesystem and automatically add the entries locally for you.

**Comment by AlexanderRavenheart** [comment]
Isn't scanning the system a job for the Lutris client? Then what is the website's part in all of this?

**Comment by RobLoach** [comment]
I assume to have the entries appear on Lutris.net as games.

**Comment by strycore** [comment]
TOSEC, No Intro and Redump are now loaded in the database.
No Lutris games are created from them because that would be kinda tricky and we already have the IGDB integration to load games from.
This is used to add games via drag and drop in the lutris client.
