### ISSUE TITLE
Misc website stuff and security note

### ISSUE THREAD

**Issue by LucasSymons** [lutris/website#278]
First posted on the [forums](https://forums.lutris.net/t/new-webste-tidy-up-stuff-security-note/4929), was suggested i come here. 

> Firstly new page is sexy and i love it, but +1 to putting a [forum link](https://forums.lutris.net/t/forums-link-should-be-on-top-of-lutris-website-prefer-dark-color-scheme/4928/2) back in the title bar. 
> 
> I didn't want to post this on git as it's not exactly an issue. just have some tools that give some good feed back in relation to best practice for a website, also helps with SEO and stuff. Just little things to tidy up. 
> 
> 1. CDN/caching, we are only caching browser side for 4 hours on most images. would be better to push that out to 24. Keeps load times down when people are moving around the site, multiple days in a row. Looks like cloudflare is not managing to do full compression on all assets as well. 
> 
> 2. Sitemap.xml / sitemap.html are missing from the site, like the favicon they should sit in the root. 
> 
> 3.  The new carousel images are taking 3+ seconds to load in, pushing the full load time of the site out. Unsure why, except looks like we are failing to use progressive rendering on one of them. 
> 
> 4. https://use.fontawesome.com/releases/v5.2.0/js/all.js is one of the largest assets on the page, if not the largest. Can we shrink it a little? because that's a lot of java.
> 
> also see links below for source of info and some other little issues. 
> 
> [Webagetest.org results](http://webpagetest.org/result/190202_ZD_88f3c51a653630258f61928b83f03a60/)
> [Nibbler Skiltide results](http://nibbler.silktide.com/en/reports/lutris.net)
> 
> also on a security side of things, we should lock down the server IP ports 80/443 to cloudflare only and move the other sites on the box to cloudflare. only took a few clicks and a curl to confirm what the origin IP for the site is and that's bad if any one ever decides to attack the site.
> 
> Also happy to help with infra stuff if and extra set of hands is needed/welcome.
>

**Comment by strycore** [comment]
This is mostly related to the old design and the Cloudflare issue isn't considered one at the moment so this can be closed.
