### ISSUE TITLE
How do I start vue?

### ISSUE THREAD

**Issue by Zeioth** [lutris/website#288]
I've been able to run the project, but now I need to build /website/frontend/vue to generate vue/dist. 

![2](https://user-images.githubusercontent.com/3357792/52483705-d9d17000-2bb4-11e9-86e1-502604076bdb.png)

So I Executed:

    nvm use node
    npm install

It didn't install webpack-cli, which is required by the project, so installed it manually: 

    npm install webpack-cli@2.0.12

It installed the version of eslint-loader 1.7.1 which throws an error, so i updated it to 2.12

    npm install eslint-loader@2.1.2

But I get the next error:

![7](https://user-images.githubusercontent.com/3357792/52523614-4622a100-2c93-11e9-8779-fb97bfe10082.png)

I've tried different versions of webpack and eslint-loader but the result is the same.

**Comment by Zeioth** [comment]
Solved by installing nvm like is described in this repository's readme.md.

**Comment by Zeioth** [comment]
After that I get a webpack error. 
![3](https://user-images.githubusercontent.com/3357792/52493735-781d0000-2bcc-11e9-8737-51a0296356ec.png)

I fixed it by editing website/frontend/vue/build/webpack.prod.conf.js like described [here](https://blog.appoptics.com/migrating-webpack-3-to-4/)

**Comment by strycore** [comment]
I use the latest, which builds fine.
You seem to have a problem with your version of webpack, maybe it's too knew.
I wrote the issue tracker in Vue 2 months ago, so it's possible for anything to change in the JS ecosystem during that time frame. WebPack is still a thing, right?

**Comment by Zeioth** [comment]
Yeah, usual JS bullshit.

I'm using this issue to document the issues I'm finding while trying to run the project in case they may be useful for someone else.

I'm getting close.
![4](https://user-images.githubusercontent.com/3357792/52494366-13fb3b80-2bce-11e9-9c47-c13f9731e974.png)

**Comment by Zeioth** [comment]
Another issue that I'll research later
![5](https://user-images.githubusercontent.com/3357792/52495975-76563b00-2bd2-11e9-8504-f1c8b65cb0c8.png)

**Comment by Zeioth** [comment]
Main post updated. This is as far as I can get. Please download this repository and try to reproduce my steps:

* git clone https://github.com/lutris/website.git
* cd ./frontend/vue
* nvm use node -> This should print 'Now using node v11.9.0 (npm v6.5.0)'
* npm install
* npm start

And in case you get missing dependency errors:

* npm install webpack-cli@3.2.2
* npm install eslint-loader@2.1.2

**Comment by strycore** [comment]
you have to run `npm run build:issues-dev` and not `npm start` that  will build the vue files.

**Comment by Zeioth** [comment]
That... Actually worked. I feel stupid for spending so much time on it. Thank you!
