### ISSUE TITLE
Unclear how (if?) you can create an issue 

### ISSUE THREAD

**Issue by Victor239** [lutris/website#290]
It's possible to reply to someone's existing comment, but it's unclear how to create a new one yourself:
![](https://i.imgur.com/QOHZydN.png)

**Comment by tannisroot** [comment]
I agree that it's not obvious and confusing, but here it is:
![peek 2019-02-13 16-01](https://user-images.githubusercontent.com/10602045/52713587-bf2e3b00-2fa8-11e9-85e9-53e51b71417a.gif)

**Comment by strycore** [comment]
Issues have been removed
