### ISSUE TITLE
Move "Support Us" to the header

### ISSUE THREAD

**Issue by tannisroot** [lutris/website#292]
IMO current "Support Us" lacks visibility as most of the attention on the website is concentrated at the top.

**Comment by tannisroot** [comment]
proof:
![image](https://user-images.githubusercontent.com/10602045/52761591-fb06e600-3024-11e9-9c37-3c31a4547915.png)

**Comment by RobLoach** [comment]
Possibly on the About Lutris page? The top many is pretty tight.

**Comment by tannisroot** [comment]
Nah it's not obvious that donation information might be in About.

**Comment by Lrss** [comment]
The information available at https://lutris.net/donate is very useful, but it doesn't seem to be linked to from anywhere. A link in the navbar would be a good idea.

**Comment by RobLoach** [comment]
Does squeeze the menu to two columns. We'll have to tweak the design a bit to make the entries fit. At the very least, I would expect it in the "The Project" section at the bottom.

![Screenshot at 2019-03-25 00-26-25](https://user-images.githubusercontent.com/25086/54895215-f0960280-4e94-11e9-9a4f-04ea57dc6038.png)

**Comment by tannisroot** [comment]
No, at the bottom is a bad idea. It has to be at the top. Also, the spacing between button is huge. I am sure it can be squeezed if in if it was reduced.
