### ISSUE TITLE
Button 'Get it from Steam' on League of Legends Site's Page

### ISSUE THREAD

**Issue by ltsdw** [lutris/website#294]
This may cause some confusion with people that doesn't know well the game.

![captura de tela de 2019-02-15 13-58-04](https://user-images.githubusercontent.com/44977415/52869085-055fd780-312c-11e9-8e67-7a96c3a10f02.png)

**Comment by tannisroot** [comment]
Well, actually, LOL does exist on Steam for unknown reasons , it's just hidden and unusable, and Lutris must be ignoring that fact and still displaying it as a Steam game.

**Comment by tannisroot** [comment]
I removed steamid entry from it. Should be fixed now.
