### ISSUE TITLE
"404 Not Found" at the tarball package.

### ISSUE THREAD

**Issue by Alexander88207** [lutris/website#296]
I just want to say that the download of the tarball package at https://lutris.net/downloads/ is not available.

**Comment by luthes** [comment]
https://github.com/lutris/website/blob/e47fbee87b8489d6ee7d708540d5a64469800543/lutrisweb/settings/base.py#L17

I think this needs to be changed to `lutris_0.5.0.1.tar.xz`

**Comment by Alexander88207** [comment]
fixed
