### ISSUE TITLE
Allows moderators to delete installers

### ISSUE THREAD

**Issue by tannisroot** [lutris/website#308]
For example, Magic the Gathering has an unpublished installer atm (I had to publish it because testing of installers is broken https://github.com/lutris/website/issues/306) and I can't do anything about it. 
https://lutris.net/games/magic-the-gathering-arena/

**Comment by tannisroot** [comment]
Maybe a solution would be to show all unpublished installers in submissions?

**Comment by strycore** [comment]
ffs I have spent days fixing that sort of bullshit

**Comment by strycore** [comment]
I have close the ticket because of the comment and because that feature was already planned to begin with
