### ISSUE TITLE
Please add link to Steam Profile privacy settings on "My account" page

### ISSUE THREAD

**Issue by Iiridayn** [lutris/website#310]
Please add link to `https://steamcommunity.com/profiles/<id>/edit/settings` on the My account page from the text "Your steam profile must be public" - might also be worth mentioning that the _"Detalles de los juegos"_ (rougly translates as "Game details" - first sub-option) must _also_ be public. My profile has always been public, but the game details were not, which prevented sync from working.

**Comment by strycore** [comment]
I added a better explanation and a screenshot of the Steam profile page.

**Comment by Iiridayn** [comment]
Sweet, thank you! I've added a PR now that you've shown the way with something a bit closer to what I had in mind for the link. I _love_ the picture - also very helpful :). :+1:
