### ISSUE TITLE
Broken icons on forums

### ISSUE THREAD

**Issue by AccountOneOff** [lutris/website#323]
Solution: https://meta.discourse.org/t/users-profile-image-not-showing-letter-avatars/109224/21

**Comment by strycore** [comment]
did the fix work for that?

**Comment by AccountOneOff** [comment]
What fix? Icons no longer broken so I guess.

**Comment by strycore** [comment]
Dunno, I remember you changed something a few days ago. It's cool if it works now :ok_hand:
