### ISSUE TITLE
Diff doesn't show up in dashboard

### ISSUE THREAD

**Issue by tannisroot** [lutris/website#326]
```TypeError: Cannot read property '0' of undefined at https://dashboard.lutris.net/static/js/chunk-8f13.c42fddc3.js:1:324654 at Object.t.api.diffview (https://dashboard.lutris.net/static/js/chunk-8f13.c42fddc3.js:1:325086) at Object.e [as mode] (https://dashboard.lutris.net/static/js/chunk-8f13.c42fddc3.js:1:498035) at a.outputDiff (https://dashboard.lutris.net/static/js/chunk-5fcf.b23c1861.js:1:1774) at a.scriptDiff (https://dashboard.lutris.net/static/js/chunk-5fcf.b23c1861.js:1:1341) at Me.get (https://dashboard.lutris.net/static/js/chunk-libs.3aa58c9a.js:18:15990) at Me.evaluate (https://dashboard.lutris.net/static/js/chunk-libs.3aa58c9a.js:18:17140) at a.scriptDiff (https://dashboard.lutris.net/static/js/chunk-libs.3aa58c9a.js:18:18982) at a.<anonymous> (https://dashboard.lutris.net/static/js/chunk-5fcf.b23c1861.js:1:5253) at a.t._render (https://dashboard.lutris.net/static/js/chunk-libs.3aa58c9a.js:18:32691)```

**Comment by strycore** [comment]
can be closed
