### ISSUE TITLE
Show drafts and submissions in the edit menu only to the submitter of them

### ISSUE THREAD

**Issue by tannisroot** [lutris/website#328]
I don't want to delete 50 drafts just to see the original approved script in the edit menu.
And no, I can't select it in the "Load a previous version" because that menu only shows up to 5 latest installers.

**Comment by strycore** [comment]
?

**Comment by tannisroot** [comment]
![image](https://user-images.githubusercontent.com/10602045/148880775-9532fcda-e2fd-44be-9679-3f68813e75eb.png)

**Comment by strycore** [comment]
I've filtered those against the current user
