### ISSUE TITLE
Make sure the docker build never breaks

### ISSUE THREAD

**Issue by Towerism** [lutris/website#337]
I'm thinking travis can do this. Travis can run the docker build in parallel that way we can isolate a breakage of the docker build from an actual failure.

**Comment by strycore** [comment]
One way of getting a stable Docker image would be to get me to use Docker for local development and production!

**Comment by Towerism** [comment]
That's true! Do you mind if I tinker with the travis.yml and submit a pull request for it? I don't know what we're using for prodution, but nevertheless I think it is a good stepping stone towards using docker in production.

On another note, I just fixed the docker build locally and will submit a pull request shortly.

**Comment by strycore** [comment]
Thanks! Until I get familiar with Docker, it's up to the community to maintain the Dockerfile so any fix is very helpful!
