### ISSUE TITLE
Use docker compose

### ISSUE THREAD

**Issue by Towerism** [lutris/website#339]
Use docker compose to accomplish two things:

- Easily connect the docker container to the host file system
- Use postgresql in a separate container from the application instead of using sqlite

**Comment by strycore** [comment]
Using sqlite should never be considered, even the development environment should run postgres. But I guess that having postgres in the container itself wouldn't work nice in prod so yeah Docker Compose would be very good to have here!

**Comment by Towerism** [comment]
Yeah, I've gotten the impression that running the database in a container is not the best idea. Also keeping them separate reduces the complexity of the containers, so that neither service actually cares whether the other is containerized.
