### ISSUE TITLE
Games with no installers don't show up in search

### ISSUE THREAD

**Issue by tannisroot** [lutris/website#347]
If a user can't find the game, how are they going to submit an installer for it then?

**Comment by testman42** [comment]
There is a "Show unpublished games" option in search options.
(for example https://lutris.net/games/?q=&unpublished-filter=on )

**Comment by tannisroot** [comment]
It's a published game. This is not related.

**Comment by tannisroot** [comment]
Indeed, it shows up with that option. 
Still an issue though. The game is clearly published, yet it doesn't show in search results.

**Comment by filbo** [comment]
The descriptive term 'unpublished' perhaps doesn't mean what the viewer expects it to.  The toggle could be called something like '[x] Show games without an installer'.

Out of curiosity, I was trying to get lists of _only_ games without installers.  There doesn't seem to be a way to do that.  As an improvement, the checkbox could be replaced with a pulldown menu:

* Show games with installers  [ default ]
* Show games without installers
* Show games with and without installers

This still wouldn't quite capture the full subtlety: games which are available for multiple platforms may (very likely) have installers for some platforms and not others.  But, close enough.

**Comment by strycore** [comment]
This is currently how the search works until we get something better.

**Comment by tannisroot** [comment]
@strycore do you really need to overhaul search for it show games without installers?

**Comment by strycore** [comment]
yes, the current one is bad
