### ISSUE TITLE
Synchronization problem

### ISSUE THREAD

**Issue by MadMagnetic** [lutris/website#348]
There`s a problem with synchronizing all of my game library and my steam games,
here`s `lutris -d` information 
![изображение](https://user-images.githubusercontent.com/34352955/55758967-ecefa780-5a60-11e9-9852-03cbc1651326.png)

**Comment by MadMagnetic** [comment]
It works! Thank`s a lot!

**Comment by MadMagnetic** [comment]
Should Lutris recognize already installed games (by native steam) and add them to the library as installed and playable or I have misunderstood?

**Comment by strycore** [comment]
if you import all those games in the import window or if you activate the sync on startup option for steam then yes, you should get all Steam games in Lutris

**Comment by MadMagnetic** [comment]
Oh, I see now. Thank again!
