### ISSUE TITLE
[GOG] Lutris fails to import certain games.

### ISSUE THREAD

**Issue by fabriciojardim** [lutris/website#351]
Lutris detects all games in my GOG library but fails to import the following:

* Duke Nukem 3D: Atomic Edition
* Fallout Classic
* Fallout 2 Classic
* Fallout Tactics Classic
* Planescape:  Torment

Manual or auto-import just fails without any error message.
This seems to be related to the title availability at the store.

* Duke Nukem 3D: Atomic Edition is currently unavailable for purchase.
* Planescape: Torment is not available for purchase (replaced by Enhanced Edition).
* The Fallout series was available, then unavailable for some time and now available again (without the 'Classics' in the title).

![Captura de tela de 2019-04-12 11-54-37](https://user-images.githubusercontent.com/29047175/56046510-d627aa00-5d19-11e9-8982-05fc2ee6c924.png)

DEBUG MESSAGES: 

* Duke Nukem 3D: Atomic Edition
DEBUG    2019-04-15 12:25:06,474 [http.get:68]:GET https://lutris.net/api/games
DEBUG    2019-04-15 12:25:06,825 [api.get_game_api_page:134]:No game found for 1207658730

* Fallout Classic:
DEBUG    2019-04-15 12:31:00,531 [http.get:68]:GET https://lutris.net/api/games
DEBUG    2019-04-15 12:31:01,548 [api.get_game_api_page:134]:No game found for 1

* Fallout 2 Classic:
DEBUG    2019-04-15 12:32:18,874 [http.get:68]:GET https://lutris.net/api/games
DEBUG    2019-04-15 12:32:19,957 [api.get_game_api_page:134]:No game found for 2

* Fallout Tactics Classic:
DEBUG    2019-04-15 12:32:44,818 [http.get:68]:GET https://lutris.net/api/games
DEBUG    2019-04-15 12:32:45,771 [api.get_game_api_page:134]:No game found for 3

* Planescape: Torment
DEBUG    2019-04-15 12:33:25,586 [http.get:68]:GET https://lutris.net/api/games
DEBUG    2019-04-15 12:33:26,610 [api.get_game_api_page:134]:No game found for 1207658887

**Comment by strycore** [comment]
GOG sync is now setup properly
