### ISSUE TITLE
Screenshots with special characters in filename return 403

### ISSUE THREAD

**Issue by AsciiWolf** [lutris/website#354]
Some screenshots that contain special character in their file name cannot be displayed. Error 403 is displayed when trying to view them. For example [this one](https://lutris.net/media/games/screenshots/Sk%C3%A4rmbild_fr%C3%A5n_2019-04-08_16-58-47.png) from World of Warcraft.

**Comment by AsciiWolf** [comment]
Still the same issue.

**Comment by AsciiWolf** [comment]
It seems that this issue has been fixed.

**Comment by AsciiWolf** [comment]
It seems that the issue is back.

**Comment by strycore** [comment]
looks ok now, and 403 errors are unlikely due to characters but by permissions
