### ISSUE TITLE
Merge/redirect entry for CorsixTH to Theme Hospital

### ISSUE THREAD

**Issue by dericke** [lutris/website#356]
I have CorsixTH installed through my distro's package manager, with game data that originally came from the copy of Theme Hospital I own on Origin. Since CorsixTH is just an alternative engine for Theme Hospital, it makes sense to me that the game would appear in my library as Theme Hospital. Instead, it detects as CorsixTH, which has a [ghost entry](https://lutris.net/games/corsixth/) in the database that doesn't appear in search results. In my mind, a game should appear the same in a user's library regardless of whether it was installed through Lutris or independently installed and subsequently detected by Lutris.

Is it possible to redirect the entry for CorsixTH to Theme Hospital, so that when detected on my system it shows up in my library as the latter?

**Comment by RobLoach** [comment]
Delete your system's one, and use https://lutris.net/games/theme-hospital/ instead?

**Comment by dericke** [comment]
The existing scripts don't work for my case because they assume a copy of the game from GOG, and mine is from Origin. Some time ago I tried submitting a script that would work with game data from other sources, but it wasn't accepted for whatever reason.

I could have another go at submitting an install script as a workaround. That wouldn't actually resolve the issue of duplicate entries in the database, though. Is it difficult to merge these two entries?

**Comment by strycore** [comment]
I merged CorsixTH with Theme Hospital and is now considered as an alias.
