### ISSUE TITLE
Nintendo Game Boy Color games don't have a default installer

### ISSUE THREAD

**Issue by tannisroot** [lutris/website#360]
For example, here is a default installer for games that have "Nintendo Game boy Advance" set as its platform. It can't be modified and is auto-created for all of them.
![image](https://user-images.githubusercontent.com/10602045/59080488-9fbd7400-88f1-11e9-982f-d50470151dd6.png)
And here is how it looks for games with "Nintendo Game boy Color" set as its platform (this isn't how it is right for this particular game as I change the platform to "Game Boy", which does produce a default installer): 
![image](https://user-images.githubusercontent.com/10602045/59080507-bc59ac00-88f1-11e9-8dd7-c29c0727ce5e.png)
As you can see, it lacks default installer and you have to write a custom one, and that doesn't work well with Mednafen runner because then "Machine Type" option is blank, which prevents the game from running unless you set it manually yourself.

**Comment by strycore** [comment]
You should have the permission to create those in the admin. Let me know if you need indications on how to proceed. (Basically, you go to Platforms, copy the default installer for GBA to GBC and make sure the Libretro core used is suitable for GBC)

**Comment by strycore** [comment]
Closing the issue since the functionality is present, no code is needed.
