### ISSUE TITLE
Inability to report duplicate game entries 

### ISSUE THREAD

**Issue by telanus** [lutris/website#364]
It's not possible to report duplicate game entries from the lutris website. As an example, you can search **Battle for Wesnoth**:
![wesnoth](https://user-images.githubusercontent.com/4029937/59154467-54cf6800-8a7b-11e9-90de-7782bcb18d1d.png)

Originally reported here: https://github.com/lutris/lutris/issues/2190 by @Steinhagen

**Comment by fgblomqvist** [comment]
The scale of the problem can be judged by #208.

**Comment by strycore** [comment]
I don't believe another tool is needed, people can just use the normal means of communication to reach out to any moderator with access to the dashboard. Merging games is very easy and quick to do.
