### ISSUE TITLE
Steam account already linked to another lutris account.

### ISSUE THREAD

**Issue by Akitakek** [lutris/website#365]
Hi,

As the title says, my [Steam Account](https://steamcommunity.com/id/AkitakeKun/) is already linked to another Lutris account (That I probably have forgotten about).
And I would like to sync my library with my current account (AkitakeKun).

I have been told by the website to contact a Lutris administrator, and asked for guidance on the Official Lutris Discord, which brought me here.
I am willing to provide any information necessary in order to be able to link my account to my current Lutris account.

Best regards,
Akitake

**Comment by strycore** [comment]
It's no longer needed to contact an adminstrator, the new account will simply take over the old one.
