### ISSUE TITLE
Script format inconsistency between the site and client

### ISSUE THREAD

**Issue by medfreeman** [lutris/website#37]
For now, when downloading a game script from the site, it is in JSON format.
So as a lutris script writer wannabee i copied the script from Warcraft III to learn and adapt it for another game.
The problem is the submit installer game screen only allows YAML format. On top of that there is no clear error message saying what is wrong.

I really have no preference about one or the other, but i think the two should be the same.
Since the [script documentation](https://github.com/lutris/lutris/blob/master/docs/installers.rst) is a bit scarce, and other scripts are always a good point of reference, i consider this important.

**Comment by strycore** [comment]
The problem isn't that one is JSON or the other YAML (JSON is valid YAML) but that the installer scripts downloaded from the website are in an array (which can contain every possible script for a game). I've written a fix to take that into account and it will soon be possible to paste directly a script into the form whether it's an array or a dict.
