### ISSUE TITLE
Blue notifications appearing on top when editing editing installers cause search to ovelap installer documentation

### ISSUE THREAD

**Issue by Faalagorn** [lutris/website#371]
When you edit installers, for example sending submissions or saving drafts, a blue message appears on top of screen and makes the whole site to move down a little, except for installer documentation which floats at the same place.

This causes the "Search" text and magnifier icon to overlap the "Installer Documentation".

Here are the screens:
![Screenshot from 2019-07-13 20-13-38](https://user-images.githubusercontent.com/4951331/61175343-ec116900-a5ad-11e9-8daf-f0c0526cf158.png)
![Screenshot from 2019-07-13 20-30-36](https://user-images.githubusercontent.com/4951331/61175344-f3387700-a5ad-11e9-8956-5a1c5ef355e9.png)

**Comment by strycore** [comment]
this no longer applies to the current design.

**Comment by Faalagorn** [comment]
> this no longer applies to the current design.

Yeah, noticed that too, I forgot I reported it back then, thanks for closing!
