### ISSUE TITLE
Default to the published version of the installer during editing

### ISSUE THREAD

**Issue by tannisroot** [lutris/website#377]
Currently, in order to edit an installer without mixing in some garbage that some users have submitted, I basically have to delete all of submissions and drafts first and only then make my changes, as the installer defaults to the latest edited version of the script and not the version that's currently published.
Instead, it should default to the currently published version, but only if there were no submissions/drafts made from the account you're currently logged in under. If there were, then the installer should default to the installer revision that was submitted by you.

**Comment by strycore** [comment]
Removed a special condition where mods would see anyone's drafts
