### ISSUE TITLE
Integrate with a distributed version control service instead of reinventing the wheel

### ISSUE THREAD

**Issue by rockerbacon** [lutris/website#379]
The currently platform offers 0 communication and version control for installers. A simple integration with a collaboration focused versioning service such as GitHub would easily solve this.

Another big problem of Lutris.net is that it currently relies on centralized moderation. Creators should be able to moderate the installers themselves, like it happens everywhere else in the open source world.

Currently I have an installer that has been outdated for over 27 days, with 3 submissions to try and get it updated. People have been publishing edits based on the outdated version while my edit never gets through and I can't get information or help anywhere, not even on the Discord server. Proper collaboration and communication must be implemented in order for the platform to grow in a healthy way.

**Comment by strycore** [comment]
This has already been discussed and it's a firm no on our end.

**Comment by strycore** [comment]
The solution is to fix what we have, it's not rocket science.
I'll take care of end when my current contract is over.

**Comment by rockerbacon** [comment]
Problem is that in order to fix what you have you'll basically reimplement a bunch of features already implemented in Git, it's extra work and extremely counter intuitive when you claim you have little time to work on this.

**Comment by strycore** [comment]
I fail to see one feature from git that would be beneficial for our use case. We have versioning already, it works. Just because it's called versioning, doesn't have to be git.

**Comment by rockerbacon** [comment]
Useful features available on both GitHub and GitLab:

- Public discussions on proposed changes;
- Requesting changes instead of just refusing/accepting merges;
- Notifications for all involved parties, on both changes and issues;
- Ability to send messages with a merge refusal/acceptance;
- Public logs of changes;
- Ability to integrate with test tools which automatically refuse broken merges;
- Synchronized edits that ensure a proposed change was always based on the latest version;
- Older codebase versions publicly available;
- Ability to easily visualize what changed from one version to another

These are the ones that immediately come to mind, there are open issues here requesting some of these features.

Proper communication and transparency among the community also opens doors for a system that requires less centralized moderation, which allows for faster growth and more assertive decisions.

**Comment by strycore** [comment]
The problem is that Github / Gitlab is not lutris.net and coding the integration between the 2 requires an insane amount of work, and I'm not touching that. We have most of those features already, some just have to be tweaked a bit to be more open to the public.

**Comment by vitaly-zdanevich** [comment]
I am also surprised to find that game scripts are not under git...

**Comment by vitaly-zdanevich** [comment]
> We have most of those features already

But no history there 
![image](https://github.com/lutris/website/assets/3514015/8a363fcf-3ecf-4a6e-b45e-fb6586f2b9f6)

**Comment by vitaly-zdanevich** [comment]
> The problem is that Github / Gitlab is not lutris.net and coding the integration between the 2 requires an insane amount of work

What if I will do that?

**Comment by strycore** [comment]
You guys are clearly not understanding how we handle scripts. Having them versioned on Git would be a MASSIVE BURDEN and a MAINTENANCE NIGHTMARE. 

You don't understand that we have tasks that can automatically fix and modify scripts.
You don't understand that almost no one needs to see an old version of a script
You don't understand that scripts are meant to be phased out in favor of metadata
You don't understand that a lot of scripts are dynamically generated. 

No of the people who have suggested git have a clear understanding of how lutris works. But you know what they say.... "When all you have is a hammer, every problem looks like a nail."

IF YOU LIKE LUTRIS AND WANT IT TO CONTUNUE, STOP ASKING FOR THE INSTALLERS TO BE IN GIT BECAUSE I WOULD RATHER SHUT DOWN THE PROJECT THAN DO THAT.

**Comment by strycore** [comment]
> What if I will do that?

We all know that's not true at all.

**Comment by strycore** [comment]
I'm trying to make good software and all I get in return is THIS!!

Lutris should be proprietary.

**Comment by strycore** [comment]
I don't get paid enough to deal with that shit.

**Comment by strycore** [comment]
You'd think that since 2016, people would stop asking to put installers in git but no it keeps coming back.

**Comment by danieljohnson2** [comment]
Well, you know, the peanut gallery is always going to peanut.

And there's no end of peanuts. It's like a [Planters](https://www.planters.com/) factory.

Try not to go nuts.

**Comment by strycore** [comment]
> Try not to go nuts.

I may be adding some dramatization to make sure the point gets across.

**Comment by strycore** [comment]
Should I block @vitaly-zdanevich from the Lutris org?

**Comment by danieljohnson2** [comment]
Not unless he's being a pest. Maybe just lock this issue.

**Comment by vitaly-zdanevich** [comment]
> You don't understand that almost no one needs to see an old version of a script

Wow, but if a script is broken?

**Comment by vitaly-zdanevich** [comment]
>  You don't understand that scripts are meant to be phased out in favor of metadata

You know, now we even use [infrastructure as code](https://en.wikipedia.org/wiki/Infrastructure_as_code) - in Terraform and other solutions, but scripts/metadata/yamls without version control is strange. And bad for any project. So why do you use git for the website? For the app?

**Comment by vitaly-zdanevich** [comment]
See, people trying to put scripts into git https://github.com/rayrapetyan/lutris_installers

**Comment by danieljohnson2** [comment]
@vitaly-zdanevich, you're being a pest. Please don't. The decision has been made, years ago, and the future direction is to *not have those scripts*, not to handle them better.

**Comment by vitaly-zdanevich** [comment]
> I'm trying to make good software and all I get in return is THIS!!

I want to make it better, safer, for all of us.

**Comment by vitaly-zdanevich** [comment]
I fels that I am afraid to contribute into Lutris scripts because they can easily be broken without version :(

**Comment by rockerbacon** [comment]
Could we get this issue locked? Me and @strycore went over everything we needed at the time and we both agree it’s not a move that’s in line with what Lutris needs. I don’t want to drag this issue any further.

**Comment by strycore** [comment]
We have versioning already in our database. It's just very rarely used and we don't have a lot of UI tools to interact with ancient revisions.

In order to provide a quick way to stop this kind of request in the future, I've added a paragraph in the FAQ: https://lutris.net/faq#git-installers

(We currently don't have a link to the FAQ on the website's layout but that's another issue that needs fixing...)
