### ISSUE TITLE
obsolete installers and no enough people to validate them

### ISSUE THREAD

**Issue by legluondunet** [lutris/website#381]
Tannis Root from Lutris team said me there is only one moderator to validate installers…it is clearly not enough: a lot of scripts are obsolete or needs maintenance, some users like me do the job but after noone validate…or severalmonths later. Then users complain about installers that do not work, even if you updated the script several weeks ago:
https://forums.lutris.net/t/source-does-not-exist-tes-arena/6862/6
https://forums.lutris.net/t/gaming-under-linux-is-still-anything-but-easy/6855/2

This situation penalizes all Lutris team work/efforts and at long-term could lose actual users or worst potential new users…Because when a script does not work, in users mind, it’s Lutris that does not work…

This last months I wrote several Lutris installers: I migrated my games libraries from POL to Lutris and I made a script for each of my game, because a lot of my games (old) need several actions, tweaks to work on Linux (with Wine, ScummVM, Dosbox...). It's a lot of work so I wanted to perpetuate this work, I didn't want to redo all these actions/tweaks every time I will install a game. Once I did this work, I would like to share it with others linux gamers that don't know or don't want write installers. By putting this work together, I avoid other players wasting time configuring their games, why would we all do the same work each on our side before playing?

So I opened a Github account and uploaded all my Lutris installers on it. It's far easier to manage installers issues on Github than in a comment at the bottom of the game page, where installer author rarely keep an eye on.

This is the ideas:
- save Lutris installers on github in his own section and users could open issues.
- warn users on the game page that an installer is indicated as non-functional with a link to the opened issue. When the issue is resolved on Github, the warning disappears and the installer is automatically updated on the game page.
- warn author that his script is indicated as non-functionnal. As he has the game and have knowledge about the installer, it's important to warn it.

It's an issue but an open discussion too, do you have others plans for installers validation?

**Comment by strycore** [comment]
Enough with putting the installers on github already. Our moderation panel work, I've spend some time accepting your installers last week.
Installers are not being moderated because no one is moderating them, that's the only reason.
