### ISSUE TITLE
Patreon badge on Discord

### ISSUE THREAD

**Issue by legluondunet** [lutris/website#384]
Hello, I don't know where to post this issue, I'm a Lutris Patreon for 6 months now and when I connect to Discord, I'm not in the Patreon list, it is not automatic?

**Comment by AccountOneOff** [comment]
https://support.patreon.com/hc/en-us/articles/212052266-How-do-I-receive-my-Discord-role-

**Comment by legluondunet** [comment]
Hello @AccountOneOff , thank you for your help, it worked after I connected my Patreon account to Discord in apps tab:
https://www.patreon.com/settings/apps
