### ISSUE TITLE
Add IGDB to the "See also:" section on game pages

### ISSUE THREAD

**Issue by ghost** [lutris/website#385]
I believe that IGDB should be in the "See also:" section because MobyGames is much more [restrictive](https://www.mobygames.com/info/faq6) with their licensing. MobyGames requires you to "credit us in anything you publish, by name (MobyGames) " for personal use and the negotiate pricing for commerical use. They also restrict the amount of screenshots you can take from the site (20) and as a result have restrictive licensing. On the other hand, IGDB freely licenses their data for personal and commercial use and will soon have one single free tier as a result of their [acquisition by Twitch](https://medium.com/igdb/we-are-joining-twitch-54cfdf44c496). As a result, a lot of popular open source game launchers use them (Playnite, Vitrine, and [planning to implement] GNOME Games).

**Comment by strycore** [comment]
We've imported all of IGDB games and added links to IGDB pages.
