### ISSUE TITLE
Game submission form has multiple broken fields

### ISSUE THREAD

**Issue by Salvatos** [lutris/website#398]
**Page:**
https://lutris.net/games/add-game/

**Specs:**
Firefox 70.0.1
Tried with and without Decentraleyes and AdblockPlus add-ons, same results.

**Issue:**
The Developer and Publisher fields cannot be populated with names not already in the dropdown. Hitting Enter or Tab without a match selected empties the field.

**Comment by Salvatos** [comment]
The Developer and Publisher fields **still** cannot be populated with names not already in the dropdown. Hitting Enter or Tab without a match selected empties the field.

**Comment by strycore** [comment]
I don't want people submitting publishers / developer studios manually. We can have that data from various sources (IGDB, mostly).
