### ISSUE TITLE
Lutris does not pull the image for Final Fantasy XIV (Steam)

### ISSUE THREAD

**Issue by yaomtc** [lutris/website#399]
I have a copy of Final Fantasy XIV installed from Steam, where it is named "FINAL FANTASY XIV Online", and that's the name Lutris gives it. I don't know how Lutris finds the images in the Lutris.net database, exactly, but this is where the method fails. Here's the entry, where it has an image:

https://lutris.net/games/final-fantasy-xiv-a-realm-reborn/

Does Lutris search by name? Maybe it would help to have the database store Steam ID as well, and use that as a secondary search function if the current search method fails.

**Comment by strycore** [comment]
We already pull the images from Steam's AppID and not the name. Also, I'm noticing that the game has a banner so I'm going to close this issue as resolved.

**Comment by yaomtc** [comment]
@strycore But it's not importing the banner when I import the game. Why?
![Screenshot_20191206_202919](https://user-images.githubusercontent.com/5534045/70366683-246c5900-1867-11ea-80a0-86dde39c4f02.png)

**Comment by strycore** [comment]
I see, it seems that the game was renamed on Steam from "A realm reborn" to just "Online"
I've created an alias on the website so you should be getting the banner now

**Comment by yaomtc** [comment]
I am now, thanks!
