### ISSUE TITLE
Innoextract should be a part of a runtime API output

### ISSUE THREAD

**Issue by rayrapetyan** [lutris/website#402]
Please add `innoextract` to https://lutris.net/api/runtime output, looks like https://github.com/lutris/lutris/blob/df3a041458d3f128f2b23837b52edbbafeec0bd2/lutris/util/extract.py#L198 expects to find it in a runtime folder.

Also, is there a backup of an SQL DB available anywhere (e.g. to run a full copy of lutris.net locally)?

Thanks.

**Comment by rayrapetyan** [comment]
https://github.com/legluondunet/MyLittleLutrisScripts/issues/15

**Comment by strycore** [comment]
There is now a database dump you can use in the releases section.

**Comment by strycore** [comment]
innoextract is in the runtime now
