### ISSUE TITLE
Possibility to flag a game as 'out to date' (like packages in Arch User Repository)

### ISSUE THREAD

**Issue by tatapoum** [lutris/website#41]
I just added 0 A.D. in my library and the installer is linked with the alpha 17.
The alpha 18 is available and I was wondering if it would be possible to implement a flag in the game page that the user could use to set the game version as 'out do date'.

**Comment by strycore** [comment]
Issues can now be reported per installer. Log in to lutris.net, find the affected installer and click "Report issue" on the dropdown menu. (I'll take care of 0AD, so no need to report it)
