### ISSUE TITLE
Links in E-Mails

### ISSUE THREAD

**Issue by modos189** [lutris/website#410]
When recovering your password, lutris will send an email with the link `https://lutris.net/user/password/reset/XXX/YYY/`

I use protonmail and it when parsing a message makes the active link all the text before `/`. The very sign `/` remains the text. So, active link is `https://lutris.net/user/password/reset/XXX/YYY`

Obviously, this does not fit under the [filter](https://github.com/lutris/website/blob/460bc84ce9f4ef566641f36f2446243750e035f8/accounts/urls.py#L24) and when I click on the link I get a 404 page.

Of course, this is not a direct Lutris problem, but similar parsing is likely in other E-Mail clients and users suffer.

If you don't mind, I would provide a PR that makes `/` optional for this link

**Comment by michaelbutler** [comment]
This is fixed now
