### ISSUE TITLE
PNG screenshots return 403

### ISSUE THREAD

**Issue by AsciiWolf** [lutris/website#413]
Most PNG screenshots cannot be displayed. Error 403 is displayed when trying to view them. For example [this one](https://lutris.net/media/games/screenshots/816905-halo-the-master-chief-collection-xbox-one-screenshot-halo.png) from Halo: The Master Chief Collection.

**Comment by AsciiWolf** [comment]
It seems that this issue has been fixed.

**Comment by AsciiWolf** [comment]
It seems that the issue is back.

**Comment by txtsd** [comment]
For example, click on the screenshot here:
https://lutris.net/games/silkroad-online/

**Comment by strycore** [comment]
should be fixed since we migrated off docker compose
