### ISSUE TITLE
page https://lutris.net/downloads/ Debian need update

### ISSUE THREAD

**Issue by sifourquier** [lutris/website#417]
Hi

On https://lutris.net/downloads/

For debian is write

echo "deb http://download.opensuse.org/repositories/home:/strycore/Debian_9.0/ ./" | sudo tee /etc/apt/sources.list.d/lutris.list
wget -q https://download.opensuse.org/repositories/home:/strycore/Debian_9.0/Release.key -O- | sudo apt-key add -

but 9.0 are not awailable on http://download.opensuse.org/repositories/home:/strycore/

need chante to

echo "deb http://download.opensuse.org/repositories/home:/strycore/Debian_10/ ./" | sudo tee /etc/apt/sources.list.d/lutris.list
wget -q https://download.opensuse.org/repositories/home:/strycore/Debian_10/Release.key -O- | sudo apt-key add -

Tanks you for your work

**Comment by tannisroot** [comment]
Fixed by https://github.com/lutris/website/commit/765f758dded8bd69e87893c3422cba79caebc1d8
