### ISSUE TITLE
Provide initial database fixtures

### ISSUE THREAD

**Issue by AlexanderRavenheart** [lutris/website#421]
Currently the Docker setup doesn't contain any entries for the standard types of data which increases development startup time due to having to manually enter required data in the database before being able to validate new development implementations.

**Comment by strycore** [comment]
that doesn't have anything to do with Docker.....

**Comment by strycore** [comment]
Database snapshots can now be downloaded on the releases pages: https://github.com/lutris/website/releases/tag/20200427
