### ISSUE TITLE
Upgrade to Django 2.2.12 (latest LTS version)

### ISSUE THREAD

**Issue by AlexanderRavenheart** [lutris/website#423]
Tasks required to enable upgrade:
- [x] Update urls.py (replace url with path or re_path accordingly):
  - [x] accounts
  - [x] bundles
  - [x] common
  - [x] emails
  - [x] games
    - [x] admin
    - [x] games
    - [x] installers
    - [x] pages
  - [x] lutrisweb
  - [x] runners
  - [x] thegamesdb
  - [x] tosec

- [x] Check admin models for inheritance of actions and replace with BaseModel.actions + [actions]
- [x] Check and update versions of django related packages

Cleanup:
- [x] Remove unused/outdated/incompatible packages from pip files:
  - [x] django-appconfig (unused)

**Comment by strycore** [comment]
We should upgrade to Django 3

**Comment by AlexanderRavenheart** [comment]
Let's take it one step at a time. Once we upgrade to latest 2.2.x version we can see what we need to do for upgrading to 3.x. There are a lot of changelogs/release notes to go through and I'd rather avoid making the jump all the way to the latest 3.x version from our outdated 2.0.5 version.

**Comment by strycore** [comment]
Alright, there should be minimal changes in the 2.2 -> 3.x migration anyway.

**Comment by AlexanderRavenheart** [comment]
PR ready for review.
