### ISSUE TITLE
New option to use steam icons

### ISSUE THREAD

**Issue by faminebadger** [lutris/website#424]
I've noticed that for (at least my) steam games, the icon file Lutris uses for its desktop and launcher files is pixelated and low quality.   However, steam itself often provides higher quality icons.

Take DOOM 2016 as an example - attached is a screenshot showing the Steam and Lutris icons next to each other (along with them both open in an image viewer).  The Steam one is noticeably higher quality, and has proper alpha transparency enabled, which the Lutris one does not.

It would be nice to have an option in the steam runner that would prefer steam icons by default (when available).  I know I can manually change the icon for a game and delete/re-create the launchers, but doing that for dozens of games isn't an attractive prospect - so I think a new option like this would be welcomed by many users (and hopefully quite simple to implement).

**Comment by Toadfield** [comment]
I have the same issue on Manjaro kde.

**Comment by strycore** [comment]
I don't see a way to fix this without a proper source of hi res icons.
