### ISSUE TITLE
Editing installers through "Admin installer" breaks diffs

### ISSUE THREAD

**Issue by tannisroot** [lutris/website#427]
Reproduction steps:
1) Edit an existing installer through "Admin Installer" menu, for example, change its rating to anything, save it
2) Approve or reject the changes in Dashboard (doesn't matter much)
3) Make some changes to the installer through "Edit installer", submit them.
4) Review the changes
If you do this, this is how the diff for this installer will look:
![Screenshot from 2020-04-24 04-08-33](https://user-images.githubusercontent.com/10602045/80266006-683eee00-86a2-11ea-810c-291b0587075a.png)
Which is obviously broken as hell and makes the diff completely useless.

**Comment by strycore** [comment]
Will be fixed in the next deploy
