### ISSUE TITLE
Docker contrainter not registering local changes

### ISSUE THREAD

**Issue by djibux** [lutris/website#433]
Hello,

I’m trying to contribute to the project but I’m facing an issue.

Setting up the container works fine and I managed to have the website up and running in no time.
However, the following sentence from the `README.rst` isn’t true for me though: "_No need to rebuild the containers for simple code changes, as the containers will pick them up from the host system._".  I currently need to explicitly rebuild the container even for simple changes like adding text to a webpage, which makes the process quite slow and tedious.

I’m new to Docker, but as I understand it, the statement `ADD . /app` from the `Dockerfile` copies the local files into the container, but it’s not keeping the changes in sync.
The `docker-compose.yml` needs to declare volumes to be mounted from the host, but only `/app/media` and `/app/templates/docs` are mounted.
I must be missing something.

I reached out for support on IRC and Discord a few days ago but got no reply, so I’m opening an issue.

Thanks.

**Comment by AlexanderRavenheart** [comment]
The fix for this is already in a PR, the one with Improved filtering and sorting

**Comment by strycore** [comment]
My take is that Docker should be used for production only but you guys have fun sorting this mess out.

**Comment by djibux** [comment]
Thanks for the feedback @AlexanderRavenheart.  Cherry picking the commit doesn't help for now: building the container fails with an error.  I'll wait for the PR to be merged.

**Comment by djibux** [comment]
Hello, I’m afraid I’m still facing an issue.  `make dev_docker` fails on `COPY src /app/src` (and indeed there is no `src` folder).  Maybe I should open a new ticket.

**Comment by AlexanderRavenheart** [comment]
@djibux Oh, sorry about that, forgot to remove that line from dev,Dockerfile when I updated the make dev_docker command. You can make an empty src folder (mkdir src) before running make dev_docker for a quick fix. I'll make a commit to fix that issue shortly.

**Comment by AlexanderRavenheart** [comment]
@djibux Made the commit to master.

**Comment by djibux** [comment]
Thanks.  `make dev_docker` now succeds but the website frontpage is broken.

I get multiple 404:
```
WARNING "GET /static/js/app.js HTTP/1.1" 404
WARNING "GET /static/css/libs.min.css HTTP/1.1" 404
…
```

**Comment by djibux** [comment]
I get those 404 for CSS and JavaScript files, not for images.

**Comment by AlexanderRavenheart** [comment]
Did you start lutrisfrontend? Is the lutrisfrontend container running?

**Comment by AlexanderRavenheart** [comment]
@djibux Can you get the latest master and test with the updated instructions specified in Readme?

**Comment by djibux** [comment]
@AlexanderRavenheart, it works with a fresh clone an the updated Readme.  Thanks!
