### ISSUE TITLE
Search not finding obvious matches

### ISSUE THREAD

**Issue by hydrian** [lutris/website#439]
Is there anything being done about Lutris's search? It is really bad. (As of 2020-05-04)

I did search for "Incredible machine" and got no results back. So I tried to add the game The Even More! Incredible Machine, it said it was already added.

I recently added the game (and it was approved), Ultima VI : The False Prophet.
I did search on it term 'ultima'. I got lots of hits for games that have the term Ultimate, but no hits on my game, Ultima VI, even though the word 'ultima' is a closer term.  There is also Ultima VII: The Black Gate that has been around for a while and wondered if the fact that my game just hadn't been indexed yet was the issue. The search didn't return that game either.

**Comment by AlexanderRavenheart** [comment]
There is a PR under review: #420

**Comment by hydrian** [comment]
This issue needs to be reopened. The #420 deployment did not fix this issue.

**Comment by AlexanderRavenheart** [comment]
@hydrian The changes are not yet deployed on the production server. The flow from github to production has been revised and all changes now go through a testing period on a staging server.

When the changes are gonna be deployed you will see the filter on the right change to this:
![image](https://user-images.githubusercontent.com/7274337/81581802-e47e4480-93b7-11ea-999a-b5a6573fab29.png)

**Comment by hydrian** [comment]
Okay Dokey
