### ISSUE TITLE
File backup

### ISSUE THREAD

**Issue by axet** [lutris/website#444]
Hello!

Game Parkan (1997) depends on intel video codecs to play in game video, can you backup this file to lutris (https://lutris.net/files/...)?

https://lutris.net/games/parkan-the-imperial-chronicles/

**Comment by strycore** [comment]
We have plans to allow users to upload files in the future but for now, if you give us the URL, I'll upload it and make it public.

**Comment by axet** [comment]
http://files.freenet.de/filepilot/fpt/video/codecs/intel_indeo_videos_codecs/iv5setup.exe

**Comment by strycore** [comment]
there you go: https://lutris.nyc3.digitaloceanspaces.com/tools/indeo/iv5setup.exe
