### ISSUE TITLE
Provide a way to create a "soft link" installer

### ISSUE THREAD

**Issue by tannisroot** [lutris/website#452]
Currently, maintaining various EGS, Origin and Battle.Net installer for different games is a bit hard - even though almost all games use pretty much identical installer, when there's need to update it, I have to go through **all** of them games that have this particular installer and update them individually, which is a pain.
The best solution here, of course, would be to create runners for those launchers, but since it's not possible atm for at least EGS (although Origin is troublesome as well), it would be nice to have some sort of "symlink" installers on Lutris.net that basically just mirror one single installer.
This way, I only have to take care of 1 installer and all the others ones will get updated along with it.
Of course, the implementation of this can be different than what I described, but you get what I'm asking for.

**Comment by AlexanderRavenheart** [comment]
We could have a multi-layered template system like: Platform template -> Store template -> Game script.
Each level would inherit settings of previous level and would be able to override steps just like we currently have the different option levels in the client.

**Comment by strycore** [comment]
I believe that our current system with the 'extends' directive is enough to achieve that.
Because those all those scripts reinstall a client like EGS, I've chosen to completely ignore those scripts in our current EGS integration and likely on the future Origin/Ubisoft integrations as well.

I believe fixing any game from a given launcher can be done through meta-data so we don't really need to create installer for all those games on Launchers.

**Comment by tannisroot** [comment]
> Because those all those scripts reinstall a client like EGS, I've chosen to completely ignore those scripts in our current EGS integration and likely on the future Origin/Ubisoft integrations as well.
That's a terrible idea, some games do require special workarounds that aren't needed for other games or harmful to them.

**Comment by strycore** [comment]
>  some games do require special workarounds that aren't needed for other games or harmful to them.

I've heard that for years and in reality, it's never the case. I don't know if I'm extremely lucky on Ubisoft Connect AND Battle.net AND Origin AND EGS AND Bethesda but this is how I've managed all my games so far.
