### ISSUE TITLE
Don't accept installers for submission that don't change anything

### ISSUE THREAD

**Issue by tannisroot** [lutris/website#453]
When reviewing stuff in dashboard, I often come across quite a few submissions that don't change anything whatsoever.
To avoid wasting moderator's time, I think website should refuse to submit installers to which 0 changes were added.

**Comment by hellohello-gif** [comment]
ok we will fix it thanks for feed back

**Comment by strycore** [comment]
let me know if you still encounter that because that should be handled by installer auto-processing
