### ISSUE TITLE
For installers, "Save Draft" instead does "Submit for Review"

### ISSUE THREAD

**Issue by Feneric** [lutris/website#458]
It looks like the "Save Draft" option for installers on the site is instead doing a "Submit for Review". I tried working on two different installers, one for a published game, one for an unpublished one, and tried to save a draft with the hope of being able to get a testable copy that I could work on further. Instead I got the message that the installer would be made public after a review. I wouldn't consider either ready for review yet.

**Comment by AlexanderRavenheart** [comment]
Yes, this "Draft" support is not implemented as expected, it needs to be reworked.

**Comment by Feneric** [comment]
OK. Apologies for submitting two premature entries to the queue.

**Comment by ZeroAbility** [comment]
If this is still a thing, I apologize for my entries, also. I submitted several yesterday. There are at least 2 game installers I need to rework. Where can I access this "queue" to download them. They are not showing up in "unpublished".

**Comment by strycore** [comment]
I've simplified the message to remove the confusion.
