### ISSUE TITLE
Too Many Requests/Throttling

### ISSUE THREAD

**Issue by telanus** [lutris/website#460]
When starting lutris it comes up with the following error:

`(2020-05-17 20:09:04,057: Unable to get games from API: Request to https://lutris.net/api/games failed: HTTP Error 429: Too Many Requests)`

thus breaking Lutris capabilities to update Game banners, Games added to the library via the website and updated runtimes. 

Also on The discord a few users said: (and I'm quoting them) 
Tony: I waited for like 6 hours yesterday to finally be able to download an install script
not doing that again
Tony: wonder if they got a traffic limiter that screws up more than it helps? dunno
N05h3ll: yup i am throttled
Tony: @TuskiDuski myself and some others have been having issues. I was able to install BL3 install script through a VPN however

**Comment by N05h3ll** [comment]
It happens on install/download requests for installation scripts .
it worked for me after about 30 times of trying to install GTA V.

**Comment by strycore** [comment]
A fix is currently being deployed
