### ISSUE TITLE
Unable to add Publisher/Developer

### ISSUE THREAD

**Issue by rfjardim** [lutris/website#470]
When we add games that are developed / published by smaller companies, there is no option to add them .. thus the game is added with those fields bank ...

I was adding this arcade game: https://en.wikipedia.org/wiki/A.D._2083

As you can see, the developer and publisher (Midcoin) are not on your DB, and we are unable to add them ...

Here is my Lutris profile ( https://lutris.net/user/kallpillar )

**Comment by strycore** [comment]
With our current integrations, we should be able to import most publishers and developers, which I prefer to letting users submit entries manually.

**Comment by Merrit** [comment]
@strycore 

> With our current integrations, we should be able to import most publishers and developers, which I prefer to letting users submit entries manually.

The integrations don't appear to be working as intended then..

See Wandersong for an example:

https://lutris.net/games/wandersong/

https://store.steampowered.com/app/530320/Wandersong/

Despite the fact that it has a listing on Steam, and the Lutris page links to that listing, the Lutris page does not have the developer or publisher info filled out - which is perhaps also why it is listed as "unpublished" and doesn't show up in regular searches even though it was released nearly 4 years ago.
