### ISSUE TITLE
Problem Building Repo

### ISSUE THREAD

**Issue by Gs-001** [lutris/website#484]
I tried building lutris website using the instruction for docker:

```
make build_dev_docker
make start_dev_docker
make init_docker_db
```

The website is running on my localhost:8000
I was looking into an issue and needed to access the shell using `make shell` but was getting the error: (Same error when i use `make test`)

```
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.
Makefile:57: recipe for target 'shell' failed
```
I have worked with django before by not with docker.
Can some body help me with verifying the basic setup.

**Comment by AlexanderRavenheart** [comment]
make shell is not configured to use the docker setup.

**Comment by Gs-001** [comment]
Then how do you run the shell through the docker setup

**Comment by AlexanderRavenheart** [comment]
I guess with something like: docker-compose exec lutrisweb make shell.
Reference link: https://docs.docker.com/compose/reference/exec/

**Comment by AlexanderRavenheart** [comment]
@strycore removed **setup** target from the makefile. I guess he didn't update the README in accordance with that change.

**Comment by strycore** [comment]
gosh.....

**Comment by strycore** [comment]
fixed here: https://github.com/lutris/website/pull/486
