### ISSUE TITLE
Mention Linux Mint on Downloads page

### ISSUE THREAD

**Issue by AsciiWolf** [lutris/website#485]
The installation instructions for Linux Mint are the same as for Ubuntu, however I think that it would still be good to add Linux Mint icon/name to the [Downloads](https://lutris.net/downloads/) page.

**Comment by strycore** [comment]
I intentionally removed Mint from the download page.

**Comment by strycore** [comment]
https://github.com/lutris/website/commit/28be8b4b8e61b7425e486903489cbd1170424509

**Comment by AsciiWolf** [comment]
Hmm, can I ask why it was removed? Linux Mint is one of the most popular (and most mature in my opinion) Linux distributions used by gamers and regular users in general.

**Comment by strycore** [comment]
Based on the number and the nature of the issues I'm receiving from Mint users, I do not believe that Mint is a mature distribution. Mind you, Mint is the *only* distro where that happens. 

If a user doesn't know that Ubuntu repos are compatible with Mint then it's better for everyone to not give them access to Lutris.

I do not want to encourage people to use Mint. This is why it's not on the download page.

**Comment by AsciiWolf** [comment]
Hmm, that's weird. I have exactly the opposite experience with Mint. :-) Most issues the users I know* had were with Ubuntu, least with Mint. My own experience is also the same as theirs (I just personally like Fedora more). But yeah, as I said, I fully respect your opinion.

[*] Around ~50 people, from regular users who do not know how to use terminal to geeks/sysadmins/programmers who are long time Linux users with deep knowledge of its internals.
