### ISSUE TITLE
Age of Empires 2 renamed

### ISSUE THREAD

**Issue by stephanlachnit** [lutris/website#495]
With the release of "Age of Empires 2: Definitive Edition", "Age of Empires 2 HD" is now called "Age of Empires (2013)". As a result, it doesn't have a banner, clicking "View on lutris.net" will take me here (https://lutris.net/games/age-of-empires-ii-2013/), even though it should point to here (https://lutris.net/games/age-of-empires-ii-hd/).
I'm not entirely sure where the data of the games for the website is stored, else I would open a PR somewhere.

**Comment by strycore** [comment]
I've created a redirect for the 2013 URL to the original one
