### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by Translator5** [lutris/website#50]
On the bottom of the Page, category Gaming News, there is a link to "LinuxGames" which is not longer active or has moved to an other address. (http://www.linuxgames.com/)

Also may we could add there "Linux Game News" -> http://linuxgamenews.com/
It is daily active and very useful!

**Comment by strycore** [comment]
Thanks for pointing that out, I've replaced the link with LinuxGameNews (just next to the *other* LGC, haha)
