### ISSUE TITLE
Please please please stop using Cloudflare. HCaptcha is broken and I cannot currently access the site. 

### ISSUE THREAD

**Issue by happysmash27** [lutris/website#515]
Some of us do not like ISPs snooping on our connection, or want to reduce risk of sites being blocked, and therefore use Tor as a proxy to browse the web. In the past couple of years, however, more and more sites have been using Cloudflare, which will require Tor users to fill out a captcha to view websites. This is very, very annoying, especially with the increasing amount of websites using it. 

Today, I tried to access Lutris.net, and like usual, it asked me to click all the planes, or boats, or whatever other annoying thing they want me to click on, except this time literally every image on HCaptcha was of what they wanted me to click, so I had to click on all of them, but they never accept my request. For minutes, I have been filling out captcha after captcha, and none are letting me in. 

Are there really so many people DDOSing your site that you _need_ a service like Cloudflare? A service that [helps create search engine monopolies](https://www.gigablast.com/blog.html#cdndanger), and makes accessing your site oh-so-annoying for those who prefer not to let their ISP see where they're going? 

Please at least _try_ to find another solution. I am sick of captchas, and it is even worse when the captchas don't even work, like today.

**Comment by happysmash27** [comment]
For anyone else experiencing this issue, I have finally gotten the site to load by reloading including cache on the captcha page with shift-ctrl-r. Even still, though, Cloudflare is a terrible solution. It still creates search engine monopolies, and this isn't the first time I've had it glitch either.

**Comment by happysmash27** [comment]
>Why can't you just use VPN? It's much faster and afaik there are (paid) VPN providers out there with which you don't need to fill captchas all the time.

My PC also hosts servers. If I use my VPN system-wide, all of my servers will no longer be accessible to the outside world. If I use network namespaces to use my VPN for my browser only, audio will not work, as Pulseaudio works over network sockets. 

As for other people, some may not be able to afford paid VPN services.

**Comment by strycore** [comment]
We have no plans to stop using Cloudflare.
