### ISSUE TITLE
Use higher quality icons and banners

### ISSUE THREAD

**Issue by tannisroot** [lutris/website#516]
Steam provides banners and icons in much higher quality that the ones we get from its API.
For instance, here are various artworks for appid 400, Portal. To get artwork for other games, simply change appid to the desirable one in the link.
https://cdn.cloudflare.steamstatic.com/steam/apps/400/header.jpg
http://cdn.steamstatic.com/steam/apps/400/library_hero.jpg
http://cdn.steamstatic.com/steam/apps/400/library_600x900_2x.jpg
http://cdn.steamstatic.com/steam/apps/400/logo.png
Icons are a bit tricky, but Joshua Ashton was kind enough to write an icon scraper and let it scrape all Steam icons out there (although it may not contain icons for games that were released very very recently):
Scraper: https://github.com/Joshua-Ashton/SteamIconGetter
Icon collection: https://release.froggi.es/steam/icons/

**Comment by strycore** [comment]
The high quality banners are downloaded directly from the lutris client
