### ISSUE TITLE
New users cannot post more than 2 links in the forum

### ISSUE THREAD

**Issue by BWPanda** [lutris/website#559]
I just registered for the [forum](https://forums.lutris.net/) so I could ask for help with a game. By my understanding, new support requests require:

- The output of `lutris --submit-issue`
- The output of `lutris -d`
- The game's debug log
- Possibly a screenshot

It's recommended to use https://paste.ubuntu.com/ for sending log data.

When I followed these steps, I got a message when trying to post my message that new users cannot post more than 2 links. So I had to remove my debug log and put it in a reply instead.

I don't think this is a very good experience for new users, especially those trying to follow the support request rules. I recommend either:

- Removing the 2-post-limit rule for new users (if possible), or
- Re-write the [instructions](https://forums.lutris.net/t/please-read-before-asking-for-help/3727) to explain how to get around this limitation.

**Comment by xlours** [comment]
I agree with this ;-)

**Comment by strycore** [comment]
In the forums settings, new users are allowed to send links.
There is a setting to limit links from the same domain, which I've increased to 6 (so you should be able to post 5 links as a new user)
