### ISSUE TITLE
Log out does not work

### ISSUE THREAD

**Issue by superbonaci** [lutris/website#564]
I click on Log out on forum, it loads these two pages consecutively:
https://forums.lutris.net/login
https://forums.lutris.net/latest

Then I'm logged in back again.

**Comment by superbonaci** [comment]
Fixed clearing cookies and site data for lutris forum, then request password reset:
[Forgot your password?](https://lutris.net/user/password/reset/)

You must enter your registration email and reset link will be sent to you.

**Comment by strycore** [comment]
The forum authentication is tied to the Lutris website authentication. If you want to log out of the forums, you'll have to log out of the lutris website as well.
