### ISSUE TITLE
Change installer "description" field to a single line

### ISSUE THREAD

**Issue by smichel17** [lutris/website#568]
**Problem**

People frequently put multiple-line technical details into the "description" field, which only renders as a single line and subsequently looks terrible where the installers are displayed.

**Potential solution**

Change "description" from a `<textarea>` to an `<input type="text">` so that people can only submit a single line. A better solution would be to have an input area that will automatically wrap but does not allow newlines. Not sure the best way to do that, though.

**Implementation**

I think this line needs to be changed, not sure whether to [`forms.TextInput`](https://docs.djangoproject.com/en/3.1/ref/forms/widgets/#django.forms.TextInput) or [`forms.charField`](https://docs.djangoproject.com/en/3.1/ref/forms/fields/#django.forms.CharField)
<https://github.com/lutris/website/blob/36cca8cbf6d2955a2e00cd57097d81348d5f583e/games/forms.py#L273>

Also the class needs to be changed, probably a new class like `installer-description` which only has `width: 100%` instead of the height, too. That would be added here:
<https://github.com/lutris/website/blob/36cca8cbf6d2955a2e00cd57097d81348d5f583e/frontend/css/lutris.less#L781>

I'm not sure that's 100% of what's needed. I would try myself but I have been putting off getting the lutris website building/running locally :P

**Workaround**

When accepting submissions, I edit the fields and cut/paste the too-long descriptions down into the notes field. Overall this is pretty easy, so it's not a pressing issue (but if the fix is just the things above, it is also easy to do).

**Comment by strycore** [comment]
fixed
