### ISSUE TITLE
WoW Audio Stutters on Wine Staging 6.10 and lutris-6.10

### ISSUE THREAD

**Issue by EvilSupahFly** [lutris/website#580]
I have encountered a problem with the audio in World of Warcraft when using both the Lutris runner and Wine HQ 6.10 branch which is not present when running the Lutris runner for 6.1 or earlier.

I ran `lutris --submit-issue` and the resultant .JSON can be seen at https://paste.ubuntu.com/p/6c6G2bQTvz/.

I also have the log files from both the "good audio" and the "bad audio" available at https://paste.ubuntu.com/p/wCgxcX5Hcc/ and https://paste.ubuntu.com/p/F95xZrrsTf/ respectively.

Since I can use an earlier WINE version, it's not super urgent, and to be honest, I'm not even sure it's a Lutris issue, but I had to start somewhere.

**Comment by dimas-cyriaco** [comment]
@EvilSupahFly I think this should be posted on https://github.com/lutris/lutris and not here. This is the repo for the website.
