### ISSUE TITLE
Submitted contributions should be reviewable and editable until moderated

### ISSUE THREAD

**Issue by theCalcaholic** [lutris/website#583]
Currently, I can neither view nor edit any changes I have submitted for an installer.
Imo, it would be better, if I were able to view and even make changes to my contribution, as long as it has not been reviewed by a moderator.
For example, lately, the lack of this functionality led to me creating 3 change requests for the same installer, because I continued to work on it after my original version (e.g. create a banner image).

**Comment by xlours** [comment]
related to https://github.com/lutris/website/issues/606 ?

**Comment by strycore** [comment]
there seems to be some mix up between installer submissions and game submissions here.
Anyway, both are now editable so this can be closed.
