### ISSUE TITLE
On game list page, don't show `Review installer` button to the moderators for drafts.

### ISSUE THREAD

**Issue by smichel17** [lutris/website#585]
![image](https://user-images.githubusercontent.com/6563664/130360473-34462ded-3b1f-49a1-8c92-4678f8a27ec1.png)

Like #232. Currently the `Review installer` button is shown when there is *any* draft. This makes it very difficult to tell whether there is a pending submission or not, and clearing out drafts is very time-consuming.

**Comment by strycore** [comment]
"review" is now only shown for submissions

**Comment by smichel17** [comment]
Thanks. Actually, this is double-fixed, because there's also the link added to the game's dashboard page, where it's not so time-consuming to clear out redundant installers :smiling_face_with_three_hearts:
