### ISSUE TITLE
steam.py fails on app manifests that do not have a top-level "name" entry in AppState

### ISSUE THREAD

**Issue by fionnb** [lutris/website#59]
I ran across this problem with "Worms Reloaded" (steam id 22600) which has the "name" property only in the UserConfig section of the manifest. Maybe there should be a fallback in the code that looks for a name in UserConfig if none is found in "AppState".

**Comment by strycore** [comment]
Thanks for the report, this is already fixed in the master branch,  Lutris 0.4.0 will not have this issue.
