### ISSUE TITLE
Please provide a Debian 11 APT repository

### ISSUE THREAD

**Issue by nodiscc** [lutris/website#590]
Hi,

Debian 11 "Bullseye" was released on 2021/08/14 (https://www.debian.org/News/2021/20210814) and Lutris provides an [openSuse build service](https://software.opensuse.org/download.html?project=home%3Astrycore&package=lutris) APT repository Debian 10 "Buster". 

Can you update the build configuration to provide a Debian 11 repository?

Thanks a lot

**Comment by strycore** [comment]
I updated the instructions on the download page to Debian 11
