### ISSUE TITLE
Game images carousel makes text jump around

### ISSUE THREAD

**Issue by bekopharm** [lutris/website#591]
Example: https://lutris.net/games/star-citizen/ has 3 images, one with a different ratio that adds more height to the screenshot box.

Result: Reading text and comments below is disturbed by jumping page that keeps adjusting the height of the image box. This is very apparent on smaller displays, like on a tablet.

Possible solution: Mebbe set a fixed height on `.screenshot` based on biggest image found in the carousel using JS or adjust the image size based on a fixed height of `.screenshot`. CSS property `object-fit: contain` or `cover` may be helpful for this.

**Comment by AlexanderRavenheart** [comment]
This should already be solved on the branch bs4-refresh which contains the next big site update.
