### ISSUE TITLE
Make the reason field mandatory

### ISSUE THREAD

**Issue by tannisroot** [lutris/website#592]
To improve the quality of submissions and understanding between the submitter and the moderator.

**Comment by strycore** [comment]
I'm not sure making it mandatory is the solution. It's going to be a pain for some

**Comment by tannisroot** [comment]
It's a pain for moderators to figure out what the hell the installer creator is changing the script for

**Comment by strycore** [comment]
You can now reject the installer with a review, which can be used to ask the author for more clarifications if needed.
