### ISSUE TITLE
"None" in new submissions

### ISSUE THREAD

**Issue by tannisroot** [lutris/website#597]
If you create a new submission and leave the field like "Description" empty, the value of that field will instead change to "None":
![image](https://user-images.githubusercontent.com/10602045/145460137-1c6f8db8-5fad-4527-9831-6fc822765a93.png)

**Comment by strycore** [comment]
The fix I had in place for this bug wasn't correct so I pushed a new one yesterday. 
Note that this doesn't remove "None" values in submissions since those are stored differently, once we have every recent submission accepted, I can clean those up again.
