### ISSUE TITLE
Remove duplicate submissions

### ISSUE THREAD

**Issue by tannisroot** [lutris/website#601]
If a user submits a game installer submission, and then the same user submits another installer submission for the same game, the older version should be removed to avoid duplicates in dashboard:
![image](https://user-images.githubusercontent.com/10602045/145478255-176f3a4c-9308-4f2b-9dc2-7925785200d7.png)

**Comment by strycore** [comment]
I have to run a task manually to clear duplicates but might make it automated to run on an hourly basis.
