### ISSUE TITLE
Unable to upload banners

### ISSUE THREAD

**Issue by tannisroot** [lutris/website#602]
See https://lutris.net/games/this-game-should-not-be-shown/
If I submit a new banner for this "game" for instance, the media will not be uploaded and the link to it will be dead
![image](https://user-images.githubusercontent.com/10602045/145480306-e6dafb22-e968-4169-b2d7-8bb8f1b4e7dd.png)

**Comment by strycore** [comment]
can confirm the upload works (the game now has a darkstalkers 3 banner)
