### ISSUE TITLE
No way to edit a new installer after submitting it.

### ISSUE THREAD

**Issue by tannisroot** [lutris/website#604]
Since the new website update, If you create a new installer and submit it, you can no longer edit it to, for example, fix a mistake, or review the draft that gets created after a submission is rejected, since the "view unpublished installers" menu is gone.
Perhaps this menu with just that new installer in it could be made visible to the submitter to fix this issue.

**Comment by xlours** [comment]
related to https://github.com/lutris/website/issues/606 ?

**Comment by strycore** [comment]
Draft and installer awaiting approval are now displayed again on the game page. Those are only displayed to staff members and the user who submitted the script.
