### ISSUE TITLE
Banner submissions look broken

### ISSUE THREAD

**Issue by tannisroot** [lutris/website#605]
I have not figured out a reliable way to reproduce this yet, but sometimes, banner submissions look really busted.
Even though the image was centered correctly, it's almost like the image gets zoomed in to the left part of it.
For instance:
https://lutris.net/games/gta-trilogy-definitive-edition/
![image](https://user-images.githubusercontent.com/10602045/145491746-a34196b9-d184-4aa8-abca-776c45fc387e.png)

**Comment by strycore** [comment]
updated code will crop the banners more reliably.
