### ISSUE TITLE
Make unpublished installers visible to moderators (on the game's page).

### ISSUE THREAD

**Issue by tannisroot** [lutris/website#606]
They are no longer visible to anyone, even mods.

**Comment by jibsaramnim** [comment]
Chiming in; I think the same applies for people who wrote the draft or not-yet-approved installer scripts, those have become invisible now with the site update.

**Comment by xlours** [comment]
Hello folks,
i agree :
i wrote a script for
https://lutris.net/games/zeus-poseidon/
but i don't see any " show unpublished installers " as in the previous version.

How can i modify my script if i can't even see it ?
best regards

**Comment by strycore** [comment]
Draft installers should now be visible to staff member and script authors.

**Comment by xlours** [comment]
> Draft installers should now be visible to staff member and script authors.

Sorry but still not visible.
see https://lutris.net/games/zeus-poseidon/ for example.

**Comment by strycore** [comment]
The query did not show installers still in draft so I adjusted that and your installers should now show up

**Comment by strycore** [comment]
If you modified an unpublished installer that you didn't create, it won't show up. This is intentional.
