### ISSUE TITLE
Sort installers by popularity on the game's page

### ISSUE THREAD

**Issue by tannisroot** [lutris/website#607]
To avoid niche installers showing up at the top of the list.

**Comment by legluondunet** [comment]
Why showing only the most populars games?
I found very interesting to see the latest updated scripts installer and new games game created on the game's page.

**Comment by tannisroot** [comment]
I don't understand your comment

**Comment by strycore** [comment]
At some point, updating the popularity would DDOS the website so I've stopped updating it a while ago. Now the client works differently so it may be safe to use again.

**Comment by strycore** [comment]
The sort by popularity is back but it's not the default (would be very easy to make it default)
