### ISSUE TITLE
updated banners games are not sync with Lutris app or website games page

### ISSUE THREAD

**Issue by legluondunet** [lutris/website#608]
I recently updated several games banners. For example, look here: https://lutris.net/games/broken-sword-the-shadow-of-the-templars/ 

on the Lutris website games page or inside Lutris interface, you have the old banner.
But if you click on "suggest changes" you can see the new banner I posted .
New banners are not sync.

**Comment by strycore** [comment]
I've sent a patch to fix this issue but you may see the old banner after a while because it gets cached by CloudFlare

with the patch in place, I can see the correct banner on lutr.is but not lutris.net

https://lutr.is/games/banner/broken-sword-the-shadow-of-the-templars.jpg
