### ISSUE TITLE
List GOG automatic installers on the game page

### ISSUE THREAD

**Issue by smichel17** [lutris/website#610]
**Problem:**

People regularly submit installers which are just "Download from gog, run/extract the installer, run the game." These are not necessary, because automatic installers exist. However, people might not realize this, because it's only possible to use automatic installers by searching in the client, not the website.

**Solution:**

Add an item to the installer list on the game page. When someone clicks it, lutris opens and runs the automatic installer for that game.

**Implementation:**

I can think of two ways to implement this:

1. Extend the `lutris:` uri scheme, with something like `lutris:gog/game_id`
    - Advantage: Leaves more to the client, so Lutris stays more offline-focused, less dependent on lutris.net.
2. Extend the installer format, with something like `install: automatic` (replaces the `install` section) and then auto-generate these installers on the website side.
    - Advantage: Allows combining the automatic installer with *some* declarative manual information. For example, if the automatic installer does not find the right exe, then someone could include that information in the installer, without having to write the full install steps.

I am not sure which option I like more. (1) is probably easier to maintain, but (2) integrates better with what we already have, and is more powerful.

**Comment by strycore** [comment]
My plan was to go with option 1 to solve this specific problem.
I do have other plans that would address what you describe in option 2: adding metadata to games that auto installers can use. This would allow auto-installers to run winetricks tasks and set file locations for the executable, but also for save games / config files.
