### ISSUE TITLE
Thumbnails black on new submitted games

### ISSUE THREAD

**Issue by maxlefou** [lutris/website#611]
When a new game is submitted, the thumbnail is all pitch black instead of using the submitted image file. Trying to reupload it doesn't fix it either. The thumbnail appears all black too in the program.

I noticed the submitted file appears on the right side of the game's page instead. This was probably intended but then, maybe it would be good to add an extra field to upload the thumbnail.

This can be visible on these new added games, [Hexxagon](https://lutris.net/games/hexxagon/) and [Terrordrome](https://lutris.net/games/terrordrome-rise-of-the-boogeymen/) (which was recently approved)

**Comment by strycore** [comment]
I've made a bunch of updates on the banner upload handler. I haven't managed to reproduce this glitch with this new setup.
