### ISSUE TITLE
Update Debian Installation Instructions to Account for Depreciation of Apt-Key

### ISSUE THREAD

**Issue by RedSoxFan04** [lutris/website#619]
Since apt-key has been depreciated in favor of GPG, the Debian instructions need to be updated. Sure, someone could look up how to make the instructions work with GPG, but it would be really nice if the instructions on the Lutris homepage were up-to-date enough that a user could just plop them into the CLI and be good to go.

**Comment by brt9023** [comment]
I was just about to report the same thing.  I'm going to submit a PR.

**Comment by RedSoxFan04** [comment]
Awesome! By the way, what’s a PR?

**Comment by brt9023** [comment]
A PR is an acronym for "pull request".  Pull requests are created when contributors want to put their changes into the remote repository. 

This is the PR that I opened: #621
