### ISSUE TITLE
not all published games show up as published

### ISSUE THREAD

**Issue by telanus** [lutris/website#62]
something I've noticed quite a few times. a Game sometimes gets published but don't show up on the game page.

For example: https://lutris.net/games/platform/sony-playstation-2 shows 11 games, but toggle the unpublished games checkbox and the game count jumps to 21 (https://lutris.net/games/platform/sony-playstation-2/?q=&unpublished-filter=on), and the 10 "unpublished" games are published

**Comment by daniel-j** [comment]
They have no installers.

**Comment by charlydelta** [comment]
I think it would be better to display games even if they don't have installers. Most of the times it is trivial to just fork some installer and you're good to go. This change would make it easier. I mean, it's obvious if a game has no installer, it's not like it would make sense to hide this from the users.

**Comment by strycore** [comment]
A lot of changes have been made since the issue was created (wee also went from 21 PS2 games to 157! :D

We also now have a pretty good flow between submissions and moderation, meaning that games usually don't go unpublished for longs periods of time.

I'll mark this issue as solved.
