### ISSUE TITLE
feature request: recently updated installers list

### ISSUE THREAD

**Issue by legluondunet** [lutris/website#629]
Hello,
could it be possible to list latest updated (and validated by moderators) installers games on he games website pages?
Could be interesting info for Lutris users.

**Comment by romulasry** [comment]
Know where the list of installers is on the website?

**Comment by strycore** [comment]
There is no list of installers aside from directly querying the REST API. 
However, all games returned in search results do have installers.

**Comment by TriMoon** [comment]
I guess the OP meant the latest updated **installer scripts**, not the executables... :wink:

**Comment by strycore** [comment]
We are now doing automated processing on scripts, so knowing which one was last updated is of little value. 
We will also migrate to a more metadata based approach for game install which means install script will no longer be needed for most cases.
As such, I don't believe exposing that info would convey any value for people who aren't Lutris moderators.
