### ISSUE TITLE
Access denied, Error code 1020

### ISSUE THREAD

**Issue by thomas725** [lutris/website#630]
I can't browse https://lutris.net/ from my home network anymore, no matter which device I use I get a mostly empty white page reading:
```
Access denied Error code 1020

You do not have access to lutris.net.

The site owner may have set restrictions that prevent you from accessing the site. Contact the site owner for access or try loading the page again.
```

Below it says the site owner can find out why I got blocked using the Ray-ID `71ca22d94dd60d5e` @ https://dash.cloudflare.com/?to=/:account/:zone/firewall

Can you help me? I guess either my provider or my specific ip adress somehow ended up blocked? I don't seem to have any issues with other cloudflare websites..

**Comment by thomas725** [comment]
I tried with my phone and my laptop, both show the same error. Using different browsers (without any addons or adblockers) show the same error too.

Yes, using a VPN to make me look like I'm coming from a different public IP-address would very likely fix the problem, but I had hoped that the owner of lutris.net would remove my IP-address from their block list, so I can access it from within my home network without any proxy / vpn trick to make me look like I'm coming from somewhere else.

**Comment by strycore** [comment]
I will need your IP address if I'm ever going to remove it from the firewall.

**Comment by strycore** [comment]
I've removed the block on AS51265 in the firewall. It may take a moment for Cloudflare to propagate the rule.
For info, any suspicious activity results in the whole Address Space getting blocked so tell your neighbors that share your address space to not do anything suspicious.

**Comment by thomas725** [comment]
Thank you! It works! None of my neighbors use this provider as far as I know, so it's more of random other people in my country who I have no influence on ;)

**Comment by speleomania** [comment]
Same issue here, happened about a month or so ago for no reason, thought it would go away on its own in a few days but it doesn't. I think this heavy-handed approach is hurting usability. The cloudflare page says to contact the site owner, but no instructions at all as to exactly how to go about doing that - kinda useless IMO. My google search landed me here, so any tips on what i need to do and why Im experiencing this issue in the first place?
Ray Id: 74fe2a0bdfeff4a2

**Comment by strycore** [comment]
If you're still blocked, send me your IP or AS Number so I can check in the Cloudflare console.

**Comment by carlosburon** [comment]
I also have the issue. I'm behind a CG-NAT so who knows what someone else is doing with my public IP.
To where should I send the IP address? Email is ok?

**Comment by speleomania** [comment]
Appears to be working now, thnks anyway

    On Tuesday, September 27, 2022 at 06:52:22 p.m. PDT, Mathieu Comandon ***@***.***> wrote:  
 
 


If you're still blocked, send me your IP or AS Number so I can check in the Cloudflare console.
