### ISSUE TITLE
Draft revision content not updating when selected

### ISSUE THREAD

**Issue by Qest333** [lutris/website#636]
Hello, i have a problem with the installer editor on the website.
When i try to change the draft to the previous revision, it switches me to the page of the selected revision but the content is not updatnig and falls back to the content of original install script. Also i cannot test the installer when i switch revisions.

I've tested this on Brave, Librewolf, Chromium and Firefox. The issue is present on all of the browsers i tested.

**Comment by strycore** [comment]
This is now fixed
