### ISSUE TITLE
Flatpak Stable release - update Download instructions

### ISSUE THREAD

**Issue by psstoyanov** [lutris/website#637]
With 0.5.11 released on the stable channel, the Download instructions should be updated.

Current:
https://github.com/lutris/website/commit/9fa5492f93502c9f1b1f46db5b32a3a2055f2e3d

Desired:
Remove flathub-beta references.

Note:
Would be good to leave the manual install command on SteamOS instructions alongside `Discover`

**Comment by strycore** [comment]
Fixed
