### ISSUE TITLE
Installer drafts disappearing

### ISSUE THREAD

**Issue by dblblaster** [lutris/website#646]
Steps to reproduce

1. Under game page click "Write a new installer"
2. Save it either using the "save draft" (it will show up in red under the game page) or "submit to moderation" (it will show up in orange under the game page).
3. Go to the game page again, find the new installer and click "Edit installer"
4. Do some edits, save draft(s), either keep as draft or click "submit to moderation", doesn't matter, they all get purged.

Wait... 24-48h or so.

The drafts will be gone.

If I am the owner of a new installer, it would be nice if I could continue to update it while it's in the moderation queue and if those updates would automatically apply to the entry under the game page (only if it's still in the queue - once approved, later updates would require moderator approval).

Example

New submission: https://lutris.net/api/installers/the-ultimate-doom-v19ud-doomwad
Update that has been lost: https://lutris.net/api/installers/games/the-ultimate-doom/revisions/93161

Thankfully I saved it, here attached: [the-ultimate-doom-v19ud-doomwad-rev93161.md](https://github.com/lutris/website/files/9836704/the-ultimate-doom-v19ud-doomwad-rev93161.md)

**Comment by cjmaxik** [comment]
Same happened to me, but I chose to delete my old draft: https://lutris.net/games/need-for-speed-underground-pc-installer-non-cd/installer/edit?revision=93435
Unfortunately, I don't have backups.

**Comment by strycore** [comment]
There are several tasks that delete drafts but it should be limited to drafts that haven't received any modification from the original so I don't see how a script you were working on could have been deleted.

Upcoming changes in how we manage installer scripts will probably result in the removal of the cleanup tasks.

**Comment by dblblaster** [comment]
I don't know, but I keep seeing it happen. All my drafts get cleaned up after some time, a day or two. I thought it may be because those were edits made to installers created by me still in the queue, but I've seen it happen with one of mine that's been approved. 

Could it be some bug where drafts get cleaned if creator and editor is the same account?

**Comment by dblblaster** [comment]
@strycore this is an edit I just submitted, would you confirm you can open it and all is in order? Later I'll ping you again when it disappears.

https://lutris.net/api/installers/games/star-wars-knights-of-the-old-republic/revisions/93423

**Comment by strycore** [comment]
This submission is perfectly fine, it should not trigger a deletion and if it did, it would already be gone as the automated cleanup process runs every hour.

I'll let this submission in the queue for now to see if anything happens to it.

**Comment by dblblaster** [comment]
It's still standing hmmm. Ok, I'll attempt to do something I may have done before, click "submit" one more time, which will submit exact same draft and see if that'll make it all get cleaned up. New one: https://lutris.net/api/installers/games/star-wars-knights-of-the-old-republic/revisions/93528

And I'll try one other thing, I want to edit one installer I have created which is still in the queue, this should disappear later, too: https://lutris.net/api/installers/games/the-ultimate-doom/revisions/93529

**Comment by dblblaster** [comment]
@strycore closing this since I can't reproduce, they're sticking around for days now. Maybe previously they were manually deleted? Or they got cleaned up because they were edits to newly created draft installers?
