### ISSUE TITLE
'mozHidden' and 'mozVisibilityState' are deprecated

### ISSUE THREAD

**Issue by Keyhaku** [lutris/website#65]
Hello,

I get this message in Firefox log:

'mozHidden' and 'mozVisibilityState' are deprecated. Please use the unprefixed 'hidden' and 'visibilityState' instead."

Take a look at the [Page Visibility API](https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API) for more info.

**Comment by strycore** [comment]
I only get this on the forums so it seems that this is a Discourse issue, you can report it here: https://github.com/discourse/discourse

**Comment by strycore** [comment]
Sorry, here: https://meta.discourse.org/c/bug as they don't use Github for the issue tracker
