### ISSUE TITLE
Origin and Ubisoft Icons are not included in the Runtime

### ISSUE THREAD

**Issue by danieljohnson2** [lutris/website#666]
When you download a new Lutris runtime, the Origin and Ubisoft icons are absent.

However, the even newer itch.io icon *is*.

The files seem to be downloadable:
[https://raw.githubusercontent.com/lutris/lutris-runtime/master/icons/hicolor/scalable/apps/origin.svg](https://raw.githubusercontent.com/lutris/lutris-runtime/master/icons/hicolor/scalable/apps/origin.svg)
[https://raw.githubusercontent.com/lutris/lutris-runtime/master/icons/hicolor/scalable/apps/ubisoft.svg](https://raw.githubusercontent.com/lutris/lutris-runtime/master/icons/hicolor/scalable/apps/ubisoft.svg)

But they aren't listed in the JSON response from [the Lutris.net api](https://lutris.net/api/runtimes/icons); I could hack a fix for this in the client, but that seems... not the intended way. I think they need to be in the Lutris.net database.

**Comment by strycore** [comment]
Icons not only need to be present on a server but they also need to be listed in the runtime API.
In that case the "icons" runtime: https://lutris.net/admin/runners/runtime/14/change/

I may have removed the Ubisoft and Origin by mistake when cleaning up the mess I made with dobharchu (https://github.com/lutris/dobharchu) a while ago.

**Comment by strycore** [comment]
I added the runtime components back
