### ISSUE TITLE
Please Remove Sexual Games

### ISSUE THREAD

**Issue by peylight** [lutris/website#676]
Hello,
I like Lutris and the purpose of it, and i want to use and help it to become bigger.
I think with the sexual games, Lutris will move away from its goals.
Lutris try to help Gamers and It is includes children but The sexual contents will damage children's health and And also it results in the hatred of families.
I think Lutris should be reviewed the content rules
Thanks

**Comment by danieljohnson2** [comment]
I think it might help to clarify that Lutris (and its website) contains no games at all; it's a catalog of known games, but it can't deliver games to you you haven't got. You get them from somewhere else, like Steam.

**Comment by strycore** [comment]
We have automatic syncing with various game database which contain games for mature audience (IGDB, GOG, ...), aside from the fact that a lot of those games have been manually submitted by the community.
There is an open ticket here https://github.com/lutris/website/issues/258 about adding a NSFW filter. With that in place, it would require a Lutris account and confirming your age to have access to +18 games. This is similar to what Steam does.

**Comment by peylight** [comment]
@danieljohnson2 Steam is hidden the sexual games by default. That mean you can't even see the title of games by searching it. But the Lutris is not doing anything?
However I think steam should be remove sexual games too.

**Comment by strycore** [comment]
Lutris is about game preservation first and keeping a database as complete as possible of all games released. I agree to hide adult games behind an age gate but we won't remove any game from our database.

**Comment by peylight** [comment]
@strycore If you can't delete, at least hide to avoid further damage.
This is very serious.

**Comment by strycore** [comment]
I have some ongoing development I have to finish first.  However, anyone is welcome to submit a PR to help speed up the process. That's why Lutris is open source.
