### ISSUE TITLE
Rework "About Lutris" statement

### ISSUE THREAD

**Issue by RobLoach** [lutris/website#68]
[On Reddit](https://www.reddit.com/r/linux_gaming/comments/5bfn4a/hows_everyone_finding_lutris/d9ofanm/), /u/itwurx4me brought up that the About Lutris section is a bit too over-ambitious.

[`website/about.html`](https://github.com/lutris/website/blob/master/templates/common/about.html#L13-L15)
> Lutris is an open source gaming platform for GNU/Linux. It allows you
        to gather and manage (install, configure and launch) all your games
        acquired from any source, in a single interface.

While that's the goal of the project, it isn't quite there yet. We should rework that sentence a bit to outline that as the project goal rather then what it does right now.

**Comment by strycore** [comment]
The about page has been rewritten
