### ISSUE TITLE
Update Twitte logo and name in footer

### ISSUE THREAD

**Issue by WebSnke** [lutris/website#685]
The footer still uses the old Twitter logo and name.

Screenshot:
![image](https://github.com/lutris/website/assets/94064167/ff2ab25e-c298-4679-8e57-a7e22c9b6a91)

**Comment by strycore** [comment]
I have resolved the issue
![image](https://github.com/lutris/website/assets/280336/a5d0a5ab-0cf7-4258-a2a8-2a96fcd6de85)
