### ISSUE TITLE
[Game] Cult Of The Lamb Suggested Changes

### ISSUE THREAD

**Issue by Rustmilian** [lutris/website#692]
[Cult Of The Lamb](https://lutris.net/games/cult-of-the-lamb)

Developer : 
Massive Monster

Icon : 
![CultOfTheLamb](https://github.com/lutris/website/assets/110098609/8e9a253e-6eb7-4baa-adbc-05c7d838762d)

Reason :
Missing Icon and Developer name.
Unable to add via Suggest changes page.

**Comment by strycore** [comment]
I've applied those changes
