### ISSUE TITLE
Can’t upload title banner

### ISSUE THREAD

**Issue by Matombo** [lutris/website#696]
Also postet on the forum because I didn't realize there is a website bugtracker: https://forums.lutris.net/t/cant-upload-title-banner-to-lutris-net/19967

Whenever I try to upload a title banner to [lutris.net](http://lutris.net/) I get the error “This is not a valid image format” as soon as I click submit.

The file has the correct dimensions (184x69) and I tried jpg, png, and webp with no luck.

**Comment by Matombo** [comment]
looking in the code: https://github.com/lutris/website/blob/2959bf46ab925feaf8560db1ea7b50bf562e2b0c/games/forms.py#L104
maybe the server is running into this? https://stackoverflow.com/questions/76616042/attributeerror-module-pil-image-has-no-attribute-antialias#answer-76616129

**Comment by D-Code** [comment]
Having the same issue. Tried multiple different formats and dimensions (184x69 and larger), but getting the same error message.

(I believe any size is accepted by the form to begin with, because the form has a cropping and positioning function that will automatically scale it down to 184x69 once submitted successfully.)

**Comment by strycore** [comment]
> looking in the code:
> 
> https://github.com/lutris/website/blob/2959bf46ab925feaf8560db1ea7b50bf562e2b0c/games/forms.py#L104
> 
> maybe the server is running into this? https://stackoverflow.com/questions/76616042/attributeerror-module-pil-image-has-no-attribute-antialias#answer-76616129

Yes this was the issue. I have updated Pillow recently and the ANTIALIAS attribute is gone.

I have updated the code and banner uploads are working again.
