### ISSUE TITLE
Can't access lutris.net

### ISSUE THREAD

**Issue by praclet** [lutris/website#697]
I'm not able to access the website https://lutris.net/
I'm seeing a message indicating that I'm blocked.

> Sorry, you have been blocked
> You are unable to access lutris.net
> 
> 
> Why have I been blocked?
> 
> This website is using a security service to protect itself from online attacks. The action you just performed triggered the security solution. There are several actions that could trigger this block including submitting a certain word or phrase, a SQL command or malformed data.
> 
> 
> What can I do to resolve this?
> 
> You can email the site owner to let them know you were blocked. Please include what you were doing when this page came up and the Cloudflare Ray ID found at the bottom of this page.

The "action I just performed" was using Firefox from a NixOS to get to the homepage on my laptop.
I'm using an internet connection via a cell phone.
The raycloud indicated is **86ec0b54da830166**

Even though I was able to install Lutris, I can't use it correctly as it needs some access to the API.

Thanks for you help.

**Comment by strycore** [comment]
Someone in France using Free Mobile has recently tried to attack the Lutris.net website. 
As a consequence, the whole Autonomous System (ASNUM) the IP of the attacker belonged to has been blocked on Cloudflare.

I can remove the block but it would be nice if in return you pledge to find and cyberbully the attacker (I don't know how, be creative).

**Comment by strycore** [comment]
I have unblocked the ASNUM.

**Comment by strycore** [comment]
The person you are supposed to hunt down uses the username zM_, owns the email  address k.rottes@gmail.com and had the IP 37.168.101.229 during the attack.

**Comment by praclet** [comment]
Many thanks for reacting so quickly. Very kind of you.

**Comment by praclet** [comment]
For legal reasons, I will not comment on your request.
Also I strongly advise that you remove said request.

You may want to reach to local authorities on that matter.

**Comment by strycore** [comment]
I don't think LAPD cares about script kiddies in France and it wasn't a request anyway, just said it would be nice.

**Comment by zquestz** [comment]
I am getting a block as well. Would love to be unblocked.

The raycloud ID is 8b5667c579c815c6

I think it is because I use hurricane electric for ipv6.

**Comment by strycore** [comment]
> I think it is because I use hurricane electric for ipv6.

I've removed AS6939 HURRICANE from the firewall block list (it was blocked because someone using that address space was running unauthorized vulnerability scans on the website)

**Comment by someone12421** [comment]
seems like its happening to everyone in israel now
#711
