### ISSUE TITLE
Game "Space Rangers" is not in Steam anymore

### ISSUE THREAD

**Issue by vitaly-zdanevich** [lutris/website#698]
https://lutris.net/games/space-rangers/

**Comment by vitaly-zdanevich** [comment]
And not in Gog.

Can I modify the script so it will download from archive.org?

**Comment by strycore** [comment]
You can but there is no way for lutris to mount disc images (assuming you'll be downloading an iso from Archive.org).

In this case it's better to let users provide their own ISO (from Archive or one they already had or made from original media) and use the insert-disc directive in the installer.

**Comment by strycore** [comment]
I see there is already a CD version. We currently don't have a way from Lutris.net to handle delisted games, looks like that would be useful in cases like this.
