### ISSUE TITLE
Issues creating account

### ISSUE THREAD

**Issue by Masked-Witch** [lutris/website#699]
I tried to create an account on lutris.net a couple of days ago and it worked for a few minutes, but I never received an email to verify my address and after a few minutes it logged me out. When I tried to log back in, the account was gone. I tried reaching out over irc but never received a response. I'm not sure what's going on

**Comment by strycore** [comment]
Do you remember the username you had? And also, did you fill out the "website" field in your profile? We have code running on the website that auto-deletes unverified account that have the website filled in since they are likely to be spam accounts.

**Comment by Masked-Witch** [comment]
Ah, that would be it then, I filled out that field while I was waiting for the email. The username was Masked_Witch and the email was maskedwitch@mailbox.org

**Comment by Masked-Witch** [comment]
I recreated my account and was able to verify my email this time. Thank you!
