### ISSUE TITLE
[Question] Targeting GoG auto-installer as `requires` 

### ISSUE THREAD

**Issue by psstoyanov** [lutris/website#705]
## Summary
Hi there!

I'm looking for information on how to target GoG auto-installer as `requires` variable.
Specifically, I'm creating an install script for [Fallout: London](https://lutris.net/games/fallout-london/) which has a dependency on [FFallout 4: Game of the Year Edition](https://lutris.net/games/fallout-4-game-of-the-year-edition/).

Currently both are auto-generated.

## Details

I've attempted two routes:
- Creating a minimal install script for Fallout: London
<details>
<summary> minimal example </summary>

```
game:
files:
- goginstaller: N/A:Select the installer from GOG
game:
  exe: _xXx_AUTO_WIN32_xXx_
  name: 'Fallout: London (Fallout 4 GOTY GOG)'
  runner: wine
  slug: fallout-london-mod-fallout-4-goty-gog
  version: '1.0'
installer:
- autosetup_gog_game: goginstaller
requires: fallout-4-game-of-the-year-edition
system:
- wine
- winetricks
- dxvk

```
</details>

This returns `No installer available.` for Fallout 4 GOTY.

So how do I target the auto-installer GoG? Do I need to create Fallout 4 GOTY installer first or?

**Comment by strycore** [comment]
You shouldn't have to give the full ID of the auto installer 

`requires: fallout-4 | fallout-4-game-of-the-year-edition` should work and if it doesn't we need to fix that.

BTW, your installer is completely wrong. Do not use _xXx_AUTO_WIN32_xXx_, do not use autosetup_gog_game, do not put the runner at the game level, do not put a version at the game level, do not add empty sections in systems.

**Comment by psstoyanov** [comment]
For the first part:
- `fallout-4` is the Steam variant installer on Lutris
  - As per the mod's own [documentation](https://fallout4london.com/release/) if the user is utilizing the Steam version, there has to be a downgrade:
  
```
Currently it is a requirement that if you own the game on Steam, for you to downgrade
Fallout 4 to the pre next gen (Fallout 4 1.10.163.0) release of the game.
```


- `fallout-4-game-of-the-year-edition` is the GoG release - there is no installer found for this specific version of the game


To avoid having to deal with the downgrade on Steam, I aimed to target the GoG version and make sure that it works there. But I can't - it throws the error that it can't find an installer for `fallout-4-game-of-the-year-edition` (even though you can find the autoinstaller: https://lutris.net/games/fallout-4-game-of-the-year-edition/ on the website).
 
This is what's failing and what confuses me. Can we target the GoG autoinstallers (ie: https://lutris.net/games/fallout-4-game-of-the-year-edition/ specifically)  or do we have to create new entry?


For the second part - thanks! I just copied what the GoG autoinstaller contained to limit the variables.

**Comment by strycore** [comment]
We would need more advanced Steam integration to be able to downgrade a game (although it should be possible) but right now it's probably better to keep the 2 games separate (at some point they will get merged)

Would setting requires to `fallout-4-game-of-the-year-edition-gog` help? Also, do you have the base game installed when installing FO: London? Because it should be picked up during the install process.

**Comment by psstoyanov** [comment]
## Fallout London talk

> We would need more advanced Steam integration to be able to downgrade a game (although it should be possible) but right now it's probably better to keep the 2 games separate (at some point they will get merged)
- Yup, precisely why I wanted to target the GoG release. Messing with a downgrade won't be easy and I would like to avoid it for now.


> Would setting requires to fallout-4-game-of-the-year-edition-gog help? Also, do you have the base game installed when installing FO: London? Because it should be picked up during the install process.
- It doesn't. This is the reason for the ticket - attempting target a game which has only the gog autoinstaller throws an error that it can't find an installer.
  -  Is there a prefix/suffix on top of the game slug, which can be used to specify that we want the gog autoinstaller?
<details>
<summary> Slimmed down installer, lutris log and screencapture </summary>

#### Slimmed down Fallout London installer
Lets start with the slimmed down Fallout London installer:
- Minimal and with the only goal to install the base game
```
game:
  name: 'Fallout: London (Fallout 4 GOTY GOG)'
  runner: wine
  slug: fallout-london-mod-fallout-4-goty-gog
  version: '1.0'
requires: fallout-4-game-of-the-year-edition

```

#### Lutris log
Here is the Lutris log - in particular, we are interested in the result of the installers for:
- `GET https://lutris.net/api/installers/game/fallout-london/revisions/20434`

```
$ lutris -d | tee fallout_london.log
2024-08-30 09:17:53,632: Unable to run command, qdbus not found
2024-08-30 09:17:53,750: The Battle.net source is unavailable because Google protobuf could not be loaded: Descriptors cannot be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
INFO     2024-08-30 09:17:53,913 [application.do_command_line:479]:Starting Lutris 0.5.17
INFO     2024-08-30 09:17:53,971 [startup.run_all_checks:120]:AMD Radeon RX 6800 (1002:73bf 1002:0e3a amdgpu) Driver 24.2.0
DEBUG    2024-08-30 09:17:54,087 [xrandr.get_resolutions:91]:Retrieving resolution list
DEBUG    2024-08-30 09:17:54,089 [xrandr._get_vidmodes:18]:Retrieving 36 video modes from XrandR
DEBUG    2024-08-30 09:17:54,146 [path_cache._update_missing_games:114]:Checking for missing games
DEBUG    2024-08-30 09:17:54,186 [api.check_stale_runtime_versions:52]:Modified at Fri 30 Aug 2024 09:02:41 , will update after Fri 30 Aug 2024 15:02:41 
DEBUG    2024-08-30 09:17:54,195 [lutriswindow.create_runtime_updater_cb:1244]:Runtime up to date
INFO     2024-08-30 09:17:58,689 [application.do_command_line:479]:Starting Lutris 0.5.17
INFO     2024-08-30 09:17:58,746 [startup.run_all_checks:120]:AMD Radeon RX 6800 (1002:73bf 1002:0e3a amdgpu) Driver 24.2.0
DEBUG    2024-08-30 09:17:58,748 [api.get_game_installers:395]:Fetching installer https://lutris.net/api/installers/game/fallout-london/revisions/20434
DEBUG    2024-08-30 09:17:58,748 [http._request:88]:GET https://lutris.net/api/installers/game/fallout-london/revisions/20434

```

#### Screencapture

[Lutris_FalloutLondon_test_script.webm](https://github.com/user-attachments/assets/909c3f83-7335-436e-b252-96c4047aa07b)


</details>



## GoG Autoinstaller talk

My example from above isn't a clean copy-paste as I did try to add the requirements of the mod.
With that said, the GoG autoinstaller tends to add: 
-  `_xXx_AUTO_WIN32_xXx_` in the `game` section
- `goginstaller: N/A:Select the installer from GOG` for `file` section
- `autosetup_gog_game: goginstaller` in the `installer` section



<details>
<summary> GoG autoinstaller examples </summary>

### A Plague Tale: Innocence

```
{
    "game": {
        "exe": "_xXx_AUTO_WIN32_xXx_"
    },
    "system": {},
    "files": [
        {
            "goginstaller": "N/A:Select the installer from GOG"
        }
    ],
    "installer": [
        {
            "autosetup_gog_game": "goginstaller"
        }
    ]
}
```

### Fallout 4: Game of the Year Edition

```
{
    "game": {
        "exe": "_xXx_AUTO_WIN32_xXx_"
    },
    "system": {},
    "files": [
        {
            "goginstaller": "N/A:Select the installer from GOG"
        }
    ],
    "installer": [
        {
            "autosetup_gog_game": "goginstaller"
        }
    ]
}
```

</details>

`_xXx_AUTO_WIN32_xXx_` felt a bit weird but I thought not to question it for now

**Comment by psstoyanov** [comment]
Interesting... Could be that the client is doing some shenanigans :thinking: 

Given that I try to install *just* Fallout 4 GOTY, it makes the same API call but somehow it knows to use the GoG autoinstaller :thinking: 

[Installing_just_Fallout_4_GOTY.webm](https://github.com/user-attachments/assets/cc39b04f-474f-414c-80a7-a3ac23502f20)

Initially I thought that the issue was with the API not returning an installer. However it could be that the client itself doesn't fallback to GoG autoinstaller for `requires` games

**Comment by psstoyanov** [comment]
This ticket could turn into Lutris client one if my last observation is indeed the source my confusion :smile:

**Comment by psstoyanov** [comment]
Thank you! This helped me understand quite a bit why and how the website functions.

I'm closing this ticket and will explore a bit how `requires` works on the client side before spawning a ticket there 👍
