### ISSUE TITLE
Blocked access to lutris.net

### ISSUE THREAD

**Issue by tangarr** [lutris/website#706]
I lost access to lutris.net from my IP address.
Cloudflare Ray ID: 8c0e94006b6dc3d3

**Comment by strycore** [comment]
>  Cloudflare Ray ID: 8c0e94006b6dc3d3

How do I use that to find your IP?

**Comment by tangarr** [comment]
> How do I use that to find your IP?
I have no idea, I never used Cloudflare.

My IP is 46.238.237.151

**Comment by strycore** [comment]
Ok, I've unblocked your IP (you can delete your last comment if you want)

**Comment by tangarr** [comment]
Thank you!
