### ISSUE TITLE
Feature request: self-hostable version of lutris.net were I can upaload my personnal games and scripts and I can register in Lutris

### ISSUE THREAD

**Issue by christophehenry** [lutris/website#707]
Lutris can already download and install games from GOG and Steam, for instance. It would be a nice feature to expand the website as a self-hotable version were I can upload my personnal games and scripts and register it as a source in Lutris, from which I can install.

**Comment by strycore** [comment]
This is currently possible to do I'm the current state of things.

**Comment by strycore** [comment]
1. Setup the website on your own domain
2. Point the lutris client to your new instance :  `website = https://...`


I do that all the time during development.

**Comment by strycore** [comment]
Also, maybe this is the feature needed : https://github.com/lutris/lutris/issues/4118

**Comment by christophehenry** [comment]
Wait you mean I can also use it to store the games themselves and there are tools to upload the game files?

**Comment by strycore** [comment]
no. For storing games themselves we have a separate feature tracked here : https://github.com/lutris/lutris/issues/4118
which will allow you to backup your games to a NAS, a USB drive or some server

You could potentially do something equivalent by self hosting a copy of lutris.net , manually managing backups and creating custom scripts.

**Comment by christophehenry** [comment]
Hey, where do I set ` website = https://...`  ? Is it mutually exclusive with having Lutris.net as a source?

**Comment by strycore** [comment]
you add it to your ~/.local/share/lutris/lutris.conf file (might be in ~/.config/lutris if your lutris install is old) 

And yes, it replaces every request to lutris.net with the newly configured website
