### ISSUE TITLE
Add Void Linux to the Download section.

### ISSUE THREAD

**Issue by sabbaghpierre** [lutris/website#708]
Lutris is available in the repos of Void Linux, and can be installed using `sudo xbps-install -S lutris`.

It would be great if a section dedicated to Void Linux could be added on the Downloads page of the website since Void is an independent distro.

**Comment by strycore** [comment]
We don't really recommend using Void for gaming so I'm not keen on adding it to the downloads page. I believe Void users are smart enough to realize they have Lutris in their repo.

**Comment by sabbaghpierre** [comment]
Fair enough, especially to the part of Void users. I just opened this issue because I recently installed Lutris and I could game just fine using it.

Thank you for your answer! I'm going to close this issue.
