### ISSUE TITLE
script: files: please add the ability to specify torrent

### ISSUE THREAD

**Issue by vitaly-zdanevich** [lutris/website#719]
Hi, as you know, we cannot buy many old games anymore, and torrent has become a history preservation platform too. We can store on archive.org - but downloading speed is poor.

And the second reason - good to have additional storage option, for long preservation.

![image](https://github.com/user-attachments/assets/da97e20c-363a-4438-91fd-ca4b68e3adfa)

About implementation: I believe that we have multiple bittorrent libs.

Thanks.

**Comment by strycore** [comment]
We don't have a way to download torrents. Download them manually outside of lutris
