### ISSUE TITLE
Game page: add icon/link to Wikidata

### ISSUE THREAD

**Issue by vitaly-zdanevich** [lutris/website#720]
Here you can see a [list of items that links to Lutris](https://www.wikidata.org/w/index.php?title=Special:WhatLinksHere/Property:P7597&limit=500) - so it would be beneficial to link back, because Wikidata items have many useful data.

**Comment by strycore** [comment]
I'm not sure what this data is but I'm pretty sure we don't need to bloat our database with it.

**Comment by strycore** [comment]
Please do not ask the Lutris team to maintain additional data. We're already swamped.
