### ISSUE TITLE
Self-hosting: publish a seed of some of Lutris.net's data

### ISSUE THREAD

**Issue by christophehenry** [lutris/website#721]
When self-hosting Lutris, adding a game relies onn adding a lot of other data (compagnies, games, genres, runners, etc.). It'd be nice if some of this data from lutris.net was published in [a Django seed](https://docs.djangoproject.com/en/5.1/howto/initial-data/).

Even better: Lutris could implement a federation protocol allowing different instances to share data (ActivityPub?). But that requires way more development.

**Comment by strycore** [comment]
We are not planning anything like that. Existing dumps of the database are available to load initial data.

**Comment by strycore** [comment]
At this point we have too much data to be able to ship that as fixtures

**Comment by christophehenry** [comment]
Can you tell me where I can find those dumps?

**Comment by christophehenry** [comment]
Thanks a lot for answering my questions. Unless I'm wrong, this export is missing images like compagnies, games and runners logos. Do you think you could take time to also publish these?

**Comment by strycore** [comment]
I'll need to update it at some point but you can get all the media up to August 2023: https://archive.org/details/lutris-media.tar
