### ISSUE TITLE
Tales of Maj'Eyal (from GOG) shows only a white screen when run through Lutris

### ISSUE THREAD

**Issue by thezerobit** [lutris/website#725]
If I run the game's executable directly, it works fine, but when I run it through Lutris the screen is completely white and unusable (the music plays) and I have to kill the process to make it exit.

Game: Tales of Maj'Eyal
Source: GOG
OS: Kubuntu 24.04.1 LTS x86_64

**Comment by danieljohnson2** [comment]
We need more information than this. Please give us the debug logs from your run.

Run ``lutris -d`` and try to start your game; then give us the console spam. There may be a clue!

**Comment by thezerobit** [comment]
Sure, I started lutris like this:

lutris -d > lutris.txt 2>&1

Started Tales of Maj'Eyal, it started up with the white screen and the music playing, I killed it with xkill and exited Lutris.

Here are the logs:
[lutris.txt](https://github.com/user-attachments/files/18216857/lutris.txt)

**Comment by danieljohnson2** [comment]
Well, I'm afraid I can't be all that helpful. It looks like most of that output is from the game, which is running, and is a native Linux game. Lutris doesn't have as much influence over that compared to a Wine game.

You might try going into the game configuration and disabling the Lutris runtime (in the System options). Perhaps there's an incompatibility there?

**Comment by danieljohnson2** [comment]
Sorry, I should have noticed that this was the wrong repo in the first place!
