### ISSUE TITLE
Installer does not exist

### ISSUE THREAD

**Issue by daniel-j** [lutris/website#81]
This game lists an installer but it can't be viewed, edited, downloaded, reported or installed:
https://lutris.net/games/2-in-1-fun-pack-dreamworks-madagascar-operation-pe/

**Comment by charlydelta** [comment]
Has this been fixed? Don't see anything unusual there.

**Comment by strycore** [comment]
Yes, I believe the issue was some platform slugs were too long, the slug is now `gba` instead of `game-boy-advance`
