### ISSUE TITLE
Remove Desura from website

### ISSUE THREAD

**Issue by daniel-j** [lutris/website#82]
The Lutris client doesn't have the desura runner anymore. Desura got merged into [OnePlay](http://www.oneplay.com) it seems.

**Comment by RobLoach** [comment]
> Desura got merged into OnePlay it seems.

Linux no longer supported? That's a shame, as that was what made it stand out from its competition.

**Comment by daniel-j** [comment]
I never used Desura and I haven't looked at OnePlay, but I'm sure they have _some_ Linux games.

**Comment by strycore** [comment]
OnePlay mostly sells Steam, Origin and Battle.net keys and their client is Windows only.

**Comment by AlexanderRavenheart** [comment]
@strycore Is this still relevant or should it be closed?

**Comment by strycore** [comment]
Removed the last reference of Desura I could find.
