### ISSUE TITLE
Add installer templates

### ISSUE THREAD

**Issue by strycore** [lutris/website#84]
Provide templates for common installers:

* Steam (already present)
* Archived native game
* Dosbox
* Emulator ROM (when no auto-installer)
* GOG
* Humble

**Comment by soredake** [comment]
I've added some templates for gog linux/windows installers in this pr https://github.com/lutris/lutris/pull/710

**Comment by strycore** [comment]
This is no longer needed. We now auto-generate installers in the lutris client for GOG / Humble / etc... 
Other methods of bulk import will be implemented in the client without the need of script.
Finally, basic templates are already available in the documentation.
