### ISSUE TITLE
Please add Holarse to the List of Linux Gaming-Websites

### ISSUE THREAD

**Issue by commel** [lutris/website#86]
We are a linux gaming website targeting german speaking audiences and trying to push linux by improving games and the use of linux as a gaming platform since now 17 years.

We would like to ask to add https://www.holarse-linuxgaming.de as "Holarse - Spielen unter Linux" to the list of linux gaming websites on https://lutris.net.

**Comment by strycore** [comment]
Done!
I don't read Holarse because I can't understand a word but it's still a major Linux gaming website :D
