### ISSUE TITLE
Make it possible to delete your own lutris.net account

### ISSUE THREAD

**Issue by Freso** [lutris/website#89]
At https://lutris.net/user/$user/edit/ I can change password, e-mail, website, …, but I can't fully remove my account. AFAICT, there aren't other places I can do this either.

**Comment by MayeulC** [comment]
It would be nice to be able to delete one's own account, I second this.

To prevent abuse (stolen password), maybe schedule the account suppression a few days later, and send out an email.

**Comment by strycore** [comment]
Yes, this would be nice. I tired of people personally email me to delete their accounts, we need to have this.

**Comment by strycore** [comment]
Closed by 550deaf3d0373db60c8bfc5aa5696940e726bbe1
