### ISSUE TITLE
Add check for indentation errors in installers.

### ISSUE THREAD

**Issue by Lucki** [lutris/website#95]
Was testing out a new installer and posted this as a new draft:

    files:
    - setup: N/A:Select the Windows installer downloaded from GOG
    - wide: http://www.wsgfmedia.com/jackfuste/Zeus/Zeus.7z
    game:
      exe: $GAMEDIR/drive_c/GOG Games/Zeus and Poseidon/Zeus.exe
      prefix: $GAMEDIR
    installer:
    - input_menu:
      description: 'Choose the desired resolution:'
      id: RESOLUTION
      options:
      - 1280x720: 1280x720
      - 1280x800: 1280x800
      - 1280x1024: 1280x1024
      - 1360x768: 1360x768
      - 1440x900: 1440x900
      - 1600x900: 1600x900
      - 1680x1050: 1680x1050
      - 1920x1080: 1920x1080
      - 1920x1200: 1920x1200
      - 2048x1152: 2048x1152
      - 2560x1440: 2560x1440
      - 2560x1600: 2560x1600
      preselect: 1920x1080
    - task:
      args: /silent /nogui /suppressmsgboxes /dir="C:\GOG Games\Zeus and Poseidon"
      executable: $setup
      name: wineexec
      prefix: $GAMEDIR
    - extract:
      dst: $CACHE
      file: $wide
    - merge:
      dst: $GAMEDIR/drive_c/GOG Games/Zeus and Poseidon
      src: $CACHE/Zeus/ZEUS_WIDE1/$INPUT_RESOLUTION

When editing it again the lines were scrambled for each task making the installer unusable:

    files:
    - setup: N/A:Select the Windows installer downloaded from GOG
    - wide: http://www.wsgfmedia.com/jackfuste/Zeus/Zeus.7z
    game:
      exe: $GAMEDIR/drive_c/GOG Games/Zeus and Poseidon/Zeus.exe
      prefix: $GAMEDIR
    installer:
    - description: 'Choose the desired resolution:'
      id: RESOLUTION
      input_menu: null
      options:
      - 1280x720: 1280x720
      - 1280x800: 1280x800
      - 1280x1024: 1280x1024
      - 1360x768: 1360x768
      - 1440x900: 1440x900
      - 1600x900: 1600x900
      - 1680x1050: 1680x1050
      - 1920x1080: 1920x1080
      - 1920x1200: 1920x1200
      - 2048x1152: 2048x1152
      - 2560x1440: 2560x1440
      - 2560x1600: 2560x1600
      preselect: 1920x1080
    - args: /silent /nogui /suppressmsgboxes /dir="C:\GOG Games\Zeus and Poseidon"
      executable: $setup
      name: wineexec
      prefix: $GAMEDIR
      task: null
    - dst: $CACHE
      extract: null
      file: $wide
    - dst: $GAMEDIR/drive_c/GOG Games/Zeus and Poseidon
      merge: null
      src: $CACHE/Zeus/ZEUS_WIDE1/$INPUT_RESOLUTION

**Comment by strycore** [comment]
This is because the initial data wasn't correctly formatted. For example: what was: 

```
- extract:
  dst: $CACHE
  file: $wide
```
should be

```
- extract:
    dst: $CACHE
    file: $wide
```
Notice the extra spaces before the dictionary keys. 
I should add a check for that in the installer validator but I have yet to figure out what your syntax resolves to.
